// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface BorderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.Border)
    com.google.protobuf.MessageOrBuilder {
}
