// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface CommonTextMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.CommonTextMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return The common.
   */
  org.example.protocol.douyin.Common getCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   */
  org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.User user = 2;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.org.example.protocol.douyin.User user = 2;</code>
   * @return The user.
   */
  org.example.protocol.douyin.User getUser();
  /**
   * <code>.org.example.protocol.douyin.User user = 2;</code>
   */
  org.example.protocol.douyin.UserOrBuilder getUserOrBuilder();

  /**
   * <code>string scene = 3;</code>
   * @return The scene.
   */
  java.lang.String getScene();
  /**
   * <code>string scene = 3;</code>
   * @return The bytes for scene.
   */
  com.google.protobuf.ByteString
      getSceneBytes();
}
