// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface DisplayControlInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.DisplayControlInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool showText = 1;</code>
   * @return The showText.
   */
  boolean getShowText();

  /**
   * <code>bool showIcons = 2;</code>
   * @return The showIcons.
   */
  boolean getShowIcons();
}
