// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface DoubleLikeDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.DoubleLikeDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool doubleFlag = 1;</code>
   * @return The doubleFlag.
   */
  boolean getDoubleFlag();

  /**
   * <code>uint32 seqId = 2;</code>
   * @return The seqId.
   */
  int getSeqId();

  /**
   * <code>uint32 renewalsNum = 3;</code>
   * @return The renewalsNum.
   */
  int getRenewalsNum();

  /**
   * <code>uint32 triggersNum = 4;</code>
   * @return The triggersNum.
   */
  int getTriggersNum();
}
