// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public final class Douyin {
  private Douyin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_Response_RouteParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_Response_RouteParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_EmojiChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_EmojiChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_ChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_LandscapeAreaCommon_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_LandscapeAreaCommon_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_RoomUserSeqMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_RoomUserSeqMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_CommonTextMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_CommonTextMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_UpdateFanTicketMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_UpdateFanTicketMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_RoomUserSeqMessageContributor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_RoomUserSeqMessageContributor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_GiftMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_GiftMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_GiftStruct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_GiftStruct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_GiftIMPriority_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_GiftIMPriority_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_TextEffect_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_TextEffect_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_TextEffectDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_TextEffectDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_MemberMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_MemberMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_PublicAreaCommon_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_PublicAreaCommon_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_EffectConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_EffectConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_EffectConfig_ExtraMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_EffectConfig_ExtraMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_Text_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_Text_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_TextPiece_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_TextPiece_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_TextPieceImage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_TextPieceImage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_TextPiecePatternRef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_TextPiecePatternRef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_TextPieceHeart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_TextPieceHeart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_TextPieceGift_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_TextPieceGift_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_PatternRef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_PatternRef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_TextPieceUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_TextPieceUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_TextFormat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_TextFormat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_LikeMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_LikeMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_SocialMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_SocialMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_PicoDisplayInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_PicoDisplayInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_DoubleLikeDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_DoubleLikeDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_DisplayControlInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_DisplayControlInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_EpisodeChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_EpisodeChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_MatchAgainstScoreMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_MatchAgainstScoreMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_Against_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_Against_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_Common_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_Common_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_PayGrade_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_PayGrade_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_FansClub_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_FansClub_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_FansClub_PreferDataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_FansClub_PreferDataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_FansClubData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_FansClubData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_UserBadge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_UserBadge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_UserBadge_IconsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_UserBadge_IconsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_GradeBuffInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_GradeBuffInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_Border_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_Border_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_GradeIcon_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_GradeIcon_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_FollowInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_FollowInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_Image_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_Image_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_NinePatchSetting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_NinePatchSetting_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_ImageContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_ImageContent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_PushFrame_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_PushFrame_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_kk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_kk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_SendMessageBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_SendMessageBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_ExtList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_ExtList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_Rsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_Rsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_Rsp_F_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_Rsp_F_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_PreMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_PreMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_HeadersList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_HeadersList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_LiveShoppingMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_LiveShoppingMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_RoomStatsMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_RoomStatsMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_ProductInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_ProductInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_CategoryInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_CategoryInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_ProductChangeMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_ProductChangeMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_ControlMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_ControlMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_FansclubMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_FansclubMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_RoomRankMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_RoomRankMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_RoomRankMessage_RoomRank_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_RoomRankMessage_RoomRank_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_RoomMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_RoomMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_RoomMessage_BuriedPointMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_RoomMessage_BuriedPointMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_protocol_douyin_RoomStreamAdaptationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_protocol_douyin_RoomStreamAdaptationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014douyin.proto\022\033org.example.protocol.dou" +
      "yin\"\216\003\n\010Response\022:\n\014messagesList\030\001 \003(\0132$" +
      ".org.example.protocol.douyin.Message\022\016\n\006" +
      "cursor\030\002 \001(\t\022\025\n\rfetchInterval\030\003 \001(\004\022\013\n\003n" +
      "ow\030\004 \001(\004\022\023\n\013internalExt\030\005 \001(\t\022\021\n\tfetchTy" +
      "pe\030\006 \001(\r\022K\n\013routeParams\030\007 \003(\01326.org.exam" +
      "ple.protocol.douyin.Response.RouteParams" +
      "Entry\022\031\n\021heartbeatDuration\030\010 \001(\004\022\017\n\007need" +
      "Ack\030\t \001(\010\022\022\n\npushServer\030\n \001(\t\022\022\n\nliveCur" +
      "sor\030\013 \001(\t\022\025\n\rhistoryNoMore\030\014 \001(\010\0322\n\020Rout" +
      "eParamsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001\"\232\001\n\007Message\022\016\n\006method\030\001 \001(\t\022\017\n\007payl" +
      "oad\030\002 \001(\014\022\r\n\005msgId\030\003 \001(\003\022\017\n\007msgType\030\004 \001(" +
      "\005\022\016\n\006offset\030\005 \001(\003\022\025\n\rneedWrdsStore\030\006 \001(\010" +
      "\022\023\n\013wrdsVersion\030\007 \001(\003\022\022\n\nwrdsSubKey\030\010 \001(" +
      "\t\"\313\002\n\020EmojiChatMessage\0223\n\006common\030\001 \001(\0132#" +
      ".org.example.protocol.douyin.Common\022/\n\004u" +
      "ser\030\002 \001(\0132!.org.example.protocol.douyin." +
      "User\022\017\n\007emojiId\030\003 \001(\003\0227\n\014emojiContent\030\004 " +
      "\001(\0132!.org.example.protocol.douyin.Text\022\026" +
      "\n\016defaultContent\030\005 \001(\t\022;\n\017backgroundImag" +
      "e\030\006 \001(\0132\".org.example.protocol.douyin.Im" +
      "age\022\024\n\014fromIntercom\030\007 \001(\010\022\034\n\024intercomHid" +
      "eUserCard\030\010 \001(\010\"\362\005\n\013ChatMessage\0223\n\006commo" +
      "n\030\001 \001(\0132#.org.example.protocol.douyin.Co" +
      "mmon\022/\n\004user\030\002 \001(\0132!.org.example.protoco" +
      "l.douyin.User\022\017\n\007content\030\003 \001(\t\022\027\n\017visibl" +
      "eToSender\030\004 \001(\010\022;\n\017backgroundImage\030\005 \001(\013" +
      "2\".org.example.protocol.douyin.Image\022\033\n\023" +
      "fullScreenTextColor\030\006 \001(\t\022=\n\021backgroundI" +
      "mageV2\030\007 \001(\0132\".org.example.protocol.douy" +
      "in.Image\022G\n\020publicAreaCommon\030\t \001(\0132-.org" +
      ".example.protocol.douyin.PublicAreaCommo" +
      "n\0225\n\tgiftImage\030\n \001(\0132\".org.example.proto" +
      "col.douyin.Image\022\022\n\nagreeMsgId\030\013 \001(\004\022\025\n\r" +
      "priorityLevel\030\014 \001(\r\022M\n\023landscapeAreaComm" +
      "on\030\r \001(\01320.org.example.protocol.douyin.L" +
      "andscapeAreaCommon\022\021\n\teventTime\030\017 \001(\004\022\022\n" +
      "\nsendReview\030\020 \001(\010\022\024\n\014fromIntercom\030\021 \001(\010\022" +
      "\034\n\024intercomHideUserCard\030\022 \001(\010\022\016\n\006chatBy\030" +
      "\024 \001(\t\022\036\n\026individualChatPriority\030\025 \001(\r\0225\n" +
      "\nrtfContent\030\026 \001(\0132!.org.example.protocol" +
      ".douyin.Text\"\266\001\n\023LandscapeAreaCommon\022\020\n\010" +
      "showHead\030\001 \001(\010\022\024\n\014showNickname\030\002 \001(\010\022\025\n\r" +
      "showFontColor\030\003 \001(\010\022\026\n\016colorValueList\030\004 " +
      "\003(\t\022H\n\023commentTypeTagsList\030\005 \003(\0162+.org.e" +
      "xample.protocol.douyin.CommentTypeTag\"\306\003" +
      "\n\022RoomUserSeqMessage\0223\n\006common\030\001 \001(\0132#.o" +
      "rg.example.protocol.douyin.Common\022M\n\tran" +
      "ksList\030\002 \003(\0132:.org.example.protocol.douy" +
      "in.RoomUserSeqMessageContributor\022\r\n\005tota" +
      "l\030\003 \001(\003\022\016\n\006popStr\030\004 \001(\t\022M\n\tseatsList\030\005 \003" +
      "(\0132:.org.example.protocol.douyin.RoomUse" +
      "rSeqMessageContributor\022\022\n\npopularity\030\006 \001" +
      "(\003\022\021\n\ttotalUser\030\007 \001(\003\022\024\n\014totalUserStr\030\010 " +
      "\001(\t\022\020\n\010totalStr\030\t \001(\t\022\033\n\023onlineUserForAn" +
      "chor\030\n \001(\t\022\030\n\020totalPvForAnchor\030\013 \001(\t\022\027\n\017" +
      "upRightStatsStr\030\014 \001(\t\022\037\n\027upRightStatsStr" +
      "Complete\030\r \001(\t\"\210\001\n\021CommonTextMessage\0223\n\006" +
      "common\030\001 \001(\0132#.org.example.protocol.douy" +
      "in.Common\022/\n\004user\030\002 \001(\0132!.org.example.pr" +
      "otocol.douyin.User\022\r\n\005scene\030\003 \001(\t\"\236\001\n\026Up" +
      "dateFanTicketMessage\0223\n\006common\030\001 \001(\0132#.o" +
      "rg.example.protocol.douyin.Common\022\036\n\026roo" +
      "mFanTicketCountText\030\002 \001(\t\022\032\n\022roomFanTick" +
      "etCount\030\003 \001(\004\022\023\n\013forceUpdate\030\004 \001(\010\"\276\001\n\035R" +
      "oomUserSeqMessageContributor\022\r\n\005score\030\001 " +
      "\001(\004\022/\n\004user\030\002 \001(\0132!.org.example.protocol" +
      ".douyin.User\022\014\n\004rank\030\003 \001(\004\022\r\n\005delta\030\004 \001(" +
      "\004\022\020\n\010isHidden\030\005 \001(\010\022\030\n\020scoreDescription\030" +
      "\006 \001(\t\022\024\n\014exactlyScore\030\007 \001(\t\"\331\007\n\013GiftMess" +
      "age\0223\n\006common\030\001 \001(\0132#.org.example.protoc" +
      "ol.douyin.Common\022\016\n\006giftId\030\002 \001(\004\022\026\n\016fanT" +
      "icketCount\030\003 \001(\004\022\022\n\ngroupCount\030\004 \001(\004\022\023\n\013" +
      "repeatCount\030\005 \001(\004\022\022\n\ncomboCount\030\006 \001(\004\022/\n" +
      "\004user\030\007 \001(\0132!.org.example.protocol.douyi" +
      "n.User\0221\n\006toUser\030\010 \001(\0132!.org.example.pro" +
      "tocol.douyin.User\022\021\n\trepeatEnd\030\t \001(\r\022;\n\n" +
      "textEffect\030\n \001(\0132\'.org.example.protocol." +
      "douyin.TextEffect\022\017\n\007groupId\030\013 \001(\004\022\027\n\017in" +
      "comeTaskgifts\030\014 \001(\004\022\032\n\022roomFanTicketCoun" +
      "t\030\r \001(\004\022=\n\010priority\030\016 \001(\0132+.org.example." +
      "protocol.douyin.GiftIMPriority\0225\n\004gift\030\017" +
      " \001(\0132\'.org.example.protocol.douyin.GiftS" +
      "truct\022\r\n\005logId\030\020 \001(\t\022\020\n\010sendType\030\021 \001(\004\022G" +
      "\n\020publicAreaCommon\030\022 \001(\0132-.org.example.p" +
      "rotocol.douyin.PublicAreaCommon\022:\n\017trayD" +
      "isplayText\030\023 \001(\0132!.org.example.protocol." +
      "douyin.Text\022\034\n\024bannedDisplayEffects\030\024 \001(" +
      "\004\022\026\n\016displayForSelf\030\031 \001(\010\022\030\n\020interactGif" +
      "tInfo\030\032 \001(\t\022\023\n\013diyItemInfo\030\033 \001(\t\022\027\n\017minA" +
      "ssetSetList\030\034 \003(\004\022\022\n\ntotalCount\030\035 \001(\004\022\030\n" +
      "\020clientGiftSource\030\036 \001(\r\022\025\n\rtoUserIdsList" +
      "\030  \003(\004\022\020\n\010sendTime\030! \001(\004\022\033\n\023forceDisplay" +
      "Effects\030\" \001(\004\022\017\n\007traceId\030# \001(\t\022\027\n\017effect" +
      "DisplayTs\030$ \001(\004\"\342\003\n\nGiftStruct\0221\n\005image\030" +
      "\001 \001(\0132\".org.example.protocol.douyin.Imag" +
      "e\022\020\n\010describe\030\002 \001(\t\022\016\n\006notify\030\003 \001(\010\022\020\n\010d" +
      "uration\030\004 \001(\004\022\n\n\002id\030\005 \001(\004\022\022\n\nforLinkmic\030" +
      "\007 \001(\010\022\016\n\006doodle\030\010 \001(\010\022\023\n\013forFansclub\030\t \001" +
      "(\010\022\r\n\005combo\030\n \001(\010\022\014\n\004type\030\013 \001(\r\022\024\n\014diamo" +
      "ndCount\030\014 \001(\r\022\032\n\022isDisplayedOnPanel\030\r \001(" +
      "\010\022\027\n\017primaryEffectId\030\016 \001(\004\0229\n\rgiftLabelI" +
      "con\030\017 \001(\0132\".org.example.protocol.douyin." +
      "Image\022\014\n\004name\030\020 \001(\t\022\016\n\006region\030\021 \001(\t\022\016\n\006m" +
      "anual\030\022 \001(\t\022\021\n\tforCustom\030\023 \001(\010\0220\n\004icon\030\025" +
      " \001(\0132\".org.example.protocol.douyin.Image" +
      "\022\022\n\nactionType\030\026 \001(\r\"U\n\016GiftIMPriority\022\026" +
      "\n\016queueSizesList\030\001 \003(\004\022\031\n\021selfQueuePrior" +
      "ity\030\002 \001(\004\022\020\n\010priority\030\003 \001(\004\"\217\001\n\nTextEffe" +
      "ct\022?\n\010portrait\030\001 \001(\0132-.org.example.proto" +
      "col.douyin.TextEffectDetail\022@\n\tlandscape" +
      "\030\002 \001(\0132-.org.example.protocol.douyin.Tex" +
      "tEffectDetail\"\340\002\n\020TextEffectDetail\022/\n\004te" +
      "xt\030\001 \001(\0132!.org.example.protocol.douyin.T" +
      "ext\022\024\n\014textFontSize\030\002 \001(\r\0226\n\nbackground\030" +
      "\003 \001(\0132\".org.example.protocol.douyin.Imag" +
      "e\022\r\n\005start\030\004 \001(\r\022\020\n\010duration\030\005 \001(\r\022\t\n\001x\030" +
      "\006 \001(\r\022\t\n\001y\030\007 \001(\r\022\r\n\005width\030\010 \001(\r\022\016\n\006heigh" +
      "t\030\t \001(\r\022\020\n\010shadowDx\030\n \001(\r\022\020\n\010shadowDy\030\013 " +
      "\001(\r\022\024\n\014shadowRadius\030\014 \001(\r\022\023\n\013shadowColor" +
      "\030\r \001(\t\022\023\n\013strokeColor\030\016 \001(\t\022\023\n\013strokeWid" +
      "th\030\017 \001(\r\"\254\006\n\rMemberMessage\0223\n\006common\030\001 \001" +
      "(\0132#.org.example.protocol.douyin.Common\022" +
      "/\n\004user\030\002 \001(\0132!.org.example.protocol.dou" +
      "yin.User\022\023\n\013memberCount\030\003 \001(\004\0223\n\010operato" +
      "r\030\004 \001(\0132!.org.example.protocol.douyin.Us" +
      "er\022\024\n\014isSetToAdmin\030\005 \001(\010\022\021\n\tisTopUser\030\006 " +
      "\001(\010\022\021\n\trankScore\030\007 \001(\004\022\021\n\ttopUserNo\030\010 \001(" +
      "\004\022\021\n\tenterType\030\t \001(\004\022\016\n\006action\030\n \001(\004\022\031\n\021" +
      "actionDescription\030\013 \001(\t\022\016\n\006userId\030\014 \001(\004\022" +
      "?\n\014effectConfig\030\r \001(\0132).org.example.prot" +
      "ocol.douyin.EffectConfig\022\016\n\006popStr\030\016 \001(\t" +
      "\022D\n\021enterEffectConfig\030\017 \001(\0132).org.exampl" +
      "e.protocol.douyin.EffectConfig\022;\n\017backgr" +
      "oundImage\030\020 \001(\0132\".org.example.protocol.d" +
      "ouyin.Image\022=\n\021backgroundImageV2\030\021 \001(\0132\"" +
      ".org.example.protocol.douyin.Image\022<\n\021an" +
      "chorDisplayText\030\022 \001(\0132!.org.example.prot" +
      "ocol.douyin.Text\022G\n\020publicAreaCommon\030\023 \001" +
      "(\0132-.org.example.protocol.douyin.PublicA" +
      "reaCommon\022\030\n\020userEnterTipType\030\024 \001(\004\022\032\n\022a" +
      "nchorEnterTipType\030\025 \001(\004\"\203\001\n\020PublicAreaCo" +
      "mmon\0225\n\tuserLabel\030\001 \001(\0132\".org.example.pr" +
      "otocol.douyin.Image\022\031\n\021userConsumeInRoom" +
      "\030\002 \001(\004\022\035\n\025userSendGiftCntInRoom\030\003 \001(\004\"\276\006" +
      "\n\014EffectConfig\022\014\n\004type\030\001 \001(\004\0220\n\004icon\030\002 \001" +
      "(\0132\".org.example.protocol.douyin.Image\022\021" +
      "\n\tavatarPos\030\003 \001(\004\022/\n\004text\030\004 \001(\0132!.org.ex" +
      "ample.protocol.douyin.Text\0224\n\010textIcon\030\005" +
      " \001(\0132\".org.example.protocol.douyin.Image" +
      "\022\020\n\010stayTime\030\006 \001(\r\022\023\n\013animAssetId\030\007 \001(\004\022" +
      "1\n\005badge\030\010 \001(\0132\".org.example.protocol.do" +
      "uyin.Image\022\034\n\024flexSettingArrayList\030\t \003(\004" +
      "\022;\n\017textIconOverlay\030\n \001(\0132\".org.example." +
      "protocol.douyin.Image\0229\n\ranimatedBadge\030\013" +
      " \001(\0132\".org.example.protocol.douyin.Image" +
      "\022\025\n\rhasSweepLight\030\014 \001(\010\022 \n\030textFlexSetti" +
      "ngArrayList\030\r \003(\004\022\031\n\021centerAnimAssetId\030\016" +
      " \001(\004\0228\n\014dynamicImage\030\017 \001(\0132\".org.example" +
      ".protocol.douyin.Image\022I\n\010extraMap\030\020 \003(\013" +
      "27.org.example.protocol.douyin.EffectCon" +
      "fig.ExtraMapEntry\022\026\n\016mp4AnimAssetId\030\021 \001(" +
      "\004\022\020\n\010priority\030\022 \001(\004\022\023\n\013maxWaitTime\030\023 \001(\004" +
      "\022\017\n\007dressId\030\024 \001(\t\022\021\n\talignment\030\025 \001(\004\022\027\n\017" +
      "alignmentOffset\030\026 \001(\004\032/\n\rExtraMapEntry\022\013" +
      "\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\246\001\n\004Text\022" +
      "\013\n\003key\030\001 \001(\t\022\025\n\rdefaultPatter\030\002 \001(\t\022>\n\rd" +
      "efaultFormat\030\003 \001(\0132\'.org.example.protoco" +
      "l.douyin.TextFormat\022:\n\npiecesList\030\004 \003(\0132" +
      "&.org.example.protocol.douyin.TextPiece\"" +
      "\262\003\n\tTextPiece\022\014\n\004type\030\001 \001(\010\0227\n\006format\030\002 " +
      "\001(\0132\'.org.example.protocol.douyin.TextFo" +
      "rmat\022\023\n\013stringValue\030\003 \001(\t\022=\n\tuserValue\030\004" +
      " \001(\0132*.org.example.protocol.douyin.TextP" +
      "ieceUser\022=\n\tgiftValue\030\005 \001(\0132*.org.exampl" +
      "e.protocol.douyin.TextPieceGift\022?\n\nheart" +
      "Value\030\006 \001(\0132+.org.example.protocol.douyi" +
      "n.TextPieceHeart\022I\n\017patternRefValue\030\007 \001(" +
      "\01320.org.example.protocol.douyin.TextPiec" +
      "ePatternRef\022?\n\nimageValue\030\010 \001(\0132+.org.ex" +
      "ample.protocol.douyin.TextPieceImage\"X\n\016" +
      "TextPieceImage\0221\n\005image\030\001 \001(\0132\".org.exam" +
      "ple.protocol.douyin.Image\022\023\n\013scalingRate" +
      "\030\002 \001(\002\":\n\023TextPiecePatternRef\022\013\n\003key\030\001 \001" +
      "(\t\022\026\n\016defaultPattern\030\002 \001(\t\"\037\n\016TextPieceH" +
      "eart\022\r\n\005color\030\001 \001(\t\"Y\n\rTextPieceGift\022\016\n\006" +
      "giftId\030\001 \001(\004\0228\n\007nameRef\030\002 \001(\0132\'.org.exam" +
      "ple.protocol.douyin.PatternRef\"1\n\nPatter" +
      "nRef\022\013\n\003key\030\001 \001(\t\022\026\n\016defaultPattern\030\002 \001(" +
      "\t\"S\n\rTextPieceUser\022/\n\004user\030\001 \001(\0132!.org.e" +
      "xample.protocol.douyin.User\022\021\n\twithColon" +
      "\030\002 \001(\010\"\243\001\n\nTextFormat\022\r\n\005color\030\001 \001(\t\022\014\n\004" +
      "bold\030\002 \001(\010\022\016\n\006italic\030\003 \001(\010\022\016\n\006weight\030\004 \001" +
      "(\r\022\023\n\013italicAngle\030\005 \001(\r\022\020\n\010fontSize\030\006 \001(" +
      "\r\022\032\n\022useHeighLightColor\030\007 \001(\010\022\025\n\ruseRemo" +
      "teClor\030\010 \001(\010\"\263\003\n\013LikeMessage\0223\n\006common\030\001" +
      " \001(\0132#.org.example.protocol.douyin.Commo" +
      "n\022\r\n\005count\030\002 \001(\004\022\r\n\005total\030\003 \001(\004\022\r\n\005color" +
      "\030\004 \001(\004\022/\n\004user\030\005 \001(\0132!.org.example.proto" +
      "col.douyin.User\022\014\n\004icon\030\006 \001(\t\022G\n\020doubleL" +
      "ikeDetail\030\007 \001(\0132-.org.example.protocol.d" +
      "ouyin.DoubleLikeDetail\022K\n\022displayControl" +
      "Info\030\010 \001(\0132/.org.example.protocol.douyin" +
      ".DisplayControlInfo\022\027\n\017linkmicGuestUid\030\t" +
      " \001(\004\022\r\n\005scene\030\n \001(\t\022E\n\017picoDisplayInfo\030\013" +
      " \001(\0132,.org.example.protocol.douyin.PicoD" +
      "isplayInfo\"\213\002\n\rSocialMessage\0223\n\006common\030\001" +
      " \001(\0132#.org.example.protocol.douyin.Commo" +
      "n\022/\n\004user\030\002 \001(\0132!.org.example.protocol.d" +
      "ouyin.User\022\021\n\tshareType\030\003 \001(\004\022\016\n\006action\030" +
      "\004 \001(\004\022\023\n\013shareTarget\030\005 \001(\t\022\023\n\013followCoun" +
      "t\030\006 \001(\004\022G\n\020publicAreaCommon\030\007 \001(\0132-.org." +
      "example.protocol.douyin.PublicAreaCommon" +
      "\"\201\001\n\017PicoDisplayInfo\022\025\n\rcomboSumCount\030\001 " +
      "\001(\004\022\r\n\005emoji\030\002 \001(\t\0225\n\temojiIcon\030\003 \001(\0132\"." +
      "org.example.protocol.douyin.Image\022\021\n\temo" +
      "jiText\030\004 \001(\t\"_\n\020DoubleLikeDetail\022\022\n\ndoub" +
      "leFlag\030\001 \001(\010\022\r\n\005seqId\030\002 \001(\r\022\023\n\013renewalsN" +
      "um\030\003 \001(\r\022\023\n\013triggersNum\030\004 \001(\r\"9\n\022Display" +
      "ControlInfo\022\020\n\010showText\030\001 \001(\010\022\021\n\tshowIco" +
      "ns\030\002 \001(\010\"\207\002\n\022EpisodeChatMessage\0224\n\006commo" +
      "n\030\001 \001(\0132$.org.example.protocol.douyin.Me" +
      "ssage\022/\n\004user\030\002 \001(\0132!.org.example.protoc" +
      "ol.douyin.User\022\017\n\007content\030\003 \001(\t\022\026\n\016visib" +
      "leToSende\030\004 \001(\010\0225\n\tgiftImage\030\007 \001(\0132\".org" +
      ".example.protocol.douyin.Image\022\022\n\nagreeM" +
      "sgId\030\010 \001(\004\022\026\n\016colorValueList\030\t \003(\t\"\262\001\n\030M" +
      "atchAgainstScoreMessage\0223\n\006common\030\001 \001(\0132" +
      "#.org.example.protocol.douyin.Common\0225\n\007" +
      "against\030\002 \001(\0132$.org.example.protocol.dou" +
      "yin.Against\022\023\n\013matchStatus\030\003 \001(\r\022\025\n\rdisp" +
      "layStatus\030\004 \001(\r\"\274\003\n\007Against\022\020\n\010leftName\030" +
      "\001 \001(\t\0224\n\010leftLogo\030\002 \001(\0132\".org.example.pr" +
      "otocol.douyin.Image\022\020\n\010leftGoal\030\003 \001(\t\022\021\n" +
      "\trightName\030\006 \001(\t\0225\n\trightLogo\030\007 \001(\0132\".or" +
      "g.example.protocol.douyin.Image\022\021\n\tright" +
      "Goal\030\010 \001(\t\022\021\n\ttimestamp\030\013 \001(\004\022\017\n\007version" +
      "\030\014 \001(\004\022\022\n\nleftTeamId\030\r \001(\004\022\023\n\013rightTeamI" +
      "d\030\016 \001(\004\022\031\n\021diffSei2absSecond\030\017 \001(\004\022\026\n\016fi" +
      "nalGoalStage\030\020 \001(\r\022\030\n\020currentGoalStage\030\021" +
      " \001(\r\022\031\n\021leftScoreAddition\030\022 \001(\r\022\032\n\022right" +
      "ScoreAddition\030\023 \001(\r\022\023\n\013leftGoalInt\030\024 \001(\004" +
      "\022\024\n\014rightGoalInt\030\025 \001(\004\"\346\003\n\006Common\022\016\n\006met" +
      "hod\030\001 \001(\t\022\r\n\005msgId\030\002 \001(\004\022\016\n\006roomId\030\003 \001(\004" +
      "\022\022\n\ncreateTime\030\004 \001(\004\022\017\n\007monitor\030\005 \001(\r\022\021\n" +
      "\tisShowMsg\030\006 \001(\010\022\020\n\010describe\030\007 \001(\t\022\020\n\010fo" +
      "ldType\030\t \001(\004\022\026\n\016anchorFoldType\030\n \001(\004\022\025\n\r" +
      "priorityScore\030\013 \001(\004\022\r\n\005logId\030\014 \001(\t\022\031\n\021ms" +
      "gProcessFilterK\030\r \001(\t\022\031\n\021msgProcessFilte" +
      "rV\030\016 \001(\t\022/\n\004user\030\017 \001(\0132!.org.example.pro" +
      "tocol.douyin.User\022\030\n\020anchorFoldTypeV2\030\021 " +
      "\001(\004\022\032\n\022processAtSeiTimeMs\030\022 \001(\004\022\030\n\020rando" +
      "mDispatchMs\030\023 \001(\004\022\022\n\nisDispatch\030\024 \001(\010\022\021\n" +
      "\tchannelId\030\025 \001(\004\022\031\n\021diffSei2absSecond\030\026 " +
      "\001(\004\022\032\n\022anchorFoldDuration\030\027 \001(\004\"\361\007\n\004User" +
      "\022\n\n\002id\030\001 \001(\004\022\017\n\007shortId\030\002 \001(\004\022\020\n\010nickNam" +
      "e\030\003 \001(\t\022\016\n\006gender\030\004 \001(\r\022\021\n\tSignature\030\005 \001" +
      "(\t\022\r\n\005Level\030\006 \001(\r\022\020\n\010Birthday\030\007 \001(\004\022\021\n\tT" +
      "elephone\030\010 \001(\t\0227\n\013AvatarThumb\030\t \001(\0132\".or" +
      "g.example.protocol.douyin.Image\0228\n\014Avata" +
      "rMedium\030\n \001(\0132\".org.example.protocol.dou" +
      "yin.Image\0227\n\013AvatarLarge\030\013 \001(\0132\".org.exa" +
      "mple.protocol.douyin.Image\022\020\n\010Verified\030\014" +
      " \001(\010\022\022\n\nExperience\030\r \001(\r\022\014\n\004city\030\016 \001(\t\022\016" +
      "\n\006Status\030\017 \001(\005\022\022\n\nCreateTime\030\020 \001(\004\022\022\n\nMo" +
      "difyTime\030\021 \001(\004\022\016\n\006Secret\030\022 \001(\r\022\026\n\016ShareQ" +
      "rcodeUri\030\023 \001(\t\022\032\n\022IncomeSharePercent\030\024 \001" +
      "(\r\022:\n\016BadgeImageList\030\025 \003(\0132\".org.example" +
      ".protocol.douyin.Image\022;\n\nFollowInfo\030\026 \001" +
      "(\0132\'.org.example.protocol.douyin.FollowI" +
      "nfo\0227\n\010PayGrade\030\027 \001(\0132%.org.example.prot" +
      "ocol.douyin.PayGrade\0227\n\010FansClub\030\030 \001(\0132%" +
      ".org.example.protocol.douyin.FansClub\022\021\n" +
      "\tSpecialId\030\032 \001(\t\0228\n\014AvatarBorder\030\033 \001(\0132\"" +
      ".org.example.protocol.douyin.Image\0221\n\005Me" +
      "dal\030\034 \001(\0132\".org.example.protocol.douyin." +
      "Image\022=\n\021RealTimeIconsList\030\035 \003(\0132\".org.e" +
      "xample.protocol.douyin.Image\022\021\n\tdisplayI" +
      "d\030& \001(\t\022\016\n\006secUid\030. \001(\t\022\027\n\016fanTicketCoun" +
      "t\030\376\007 \001(\004\022\016\n\005idStr\030\204\010 \001(\t\022\021\n\010ageRange\030\225\010 " +
      "\001(\r\"\210\t\n\010PayGrade\022\031\n\021totalDiamondCount\030\001 " +
      "\001(\003\0227\n\013diamondIcon\030\002 \001(\0132\".org.example.p" +
      "rotocol.douyin.Image\022\014\n\004name\030\003 \001(\t\0220\n\004ic" +
      "on\030\004 \001(\0132\".org.example.protocol.douyin.I" +
      "mage\022\020\n\010nextName\030\005 \001(\t\022\r\n\005level\030\006 \001(\003\0224\n" +
      "\010nextIcon\030\007 \001(\0132\".org.example.protocol.d" +
      "ouyin.Image\022\023\n\013nextDiamond\030\010 \001(\003\022\022\n\nnowD" +
      "iamond\030\t \001(\003\022\033\n\023thisGradeMinDiamond\030\n \001(" +
      "\003\022\033\n\023thisGradeMaxDiamond\030\013 \001(\003\022\025\n\rpayDia" +
      "mondBak\030\014 \001(\003\022\025\n\rgradeDescribe\030\r \001(\t\022=\n\r" +
      "gradeIconList\030\016 \003(\0132&.org.example.protoc" +
      "ol.douyin.GradeIcon\022\026\n\016screenChatType\030\017 " +
      "\001(\003\0222\n\006imIcon\030\020 \001(\0132\".org.example.protoc" +
      "ol.douyin.Image\022;\n\017imIconWithLevel\030\021 \001(\013" +
      "2\".org.example.protocol.douyin.Image\0224\n\010" +
      "liveIcon\030\022 \001(\0132\".org.example.protocol.do" +
      "uyin.Image\022>\n\022newImIconWithLevel\030\023 \001(\0132\"" +
      ".org.example.protocol.douyin.Image\0227\n\013ne" +
      "wLiveIcon\030\024 \001(\0132\".org.example.protocol.d" +
      "ouyin.Image\022\032\n\022upgradeNeedConsume\030\025 \001(\003\022" +
      "\026\n\016nextPrivileges\030\026 \001(\t\0226\n\nbackground\030\027 " +
      "\001(\0132\".org.example.protocol.douyin.Image\022" +
      ":\n\016backgroundBack\030\030 \001(\0132\".org.example.pr" +
      "otocol.douyin.Image\022\r\n\005score\030\031 \001(\003\022<\n\010bu" +
      "ffInfo\030\032 \001(\0132*.org.example.protocol.douy" +
      "in.GradeBuffInfo\022\024\n\013gradeBanner\030\351\007 \001(\t\022<" +
      "\n\017profileDialogBg\030\352\007 \001(\0132\".org.example.p" +
      "rotocol.douyin.Image\022@\n\023profileDialogBgB" +
      "ack\030\353\007 \001(\0132\".org.example.protocol.douyin" +
      ".Image\"\354\001\n\010FansClub\0227\n\004data\030\001 \001(\0132).org." +
      "example.protocol.douyin.FansClubData\022I\n\n" +
      "preferData\030\002 \003(\01325.org.example.protocol." +
      "douyin.FansClub.PreferDataEntry\032\\\n\017Prefe" +
      "rDataEntry\022\013\n\003key\030\001 \001(\005\0228\n\005value\030\002 \001(\0132)" +
      ".org.example.protocol.douyin.FansClubDat" +
      "a:\0028\001\"\256\001\n\014FansClubData\022\020\n\010clubName\030\001 \001(\t" +
      "\022\r\n\005level\030\002 \001(\005\022\032\n\022userFansClubStatus\030\003 " +
      "\001(\005\0225\n\005badge\030\004 \001(\0132&.org.example.protoco" +
      "l.douyin.UserBadge\022\030\n\020availableGiftIds\030\005" +
      " \003(\003\022\020\n\010anchorId\030\006 \001(\003\"\256\001\n\tUserBadge\022@\n\005" +
      "icons\030\001 \003(\01321.org.example.protocol.douyi" +
      "n.UserBadge.IconsEntry\022\r\n\005title\030\002 \001(\t\032P\n" +
      "\nIconsEntry\022\013\n\003key\030\001 \001(\005\0221\n\005value\030\002 \001(\0132" +
      "\".org.example.protocol.douyin.Image:\0028\001\"" +
      "\017\n\rGradeBuffInfo\"\010\n\006Border\"s\n\tGradeIcon\022" +
      "0\n\004icon\030\001 \001(\0132\".org.example.protocol.dou" +
      "yin.Image\022\023\n\013iconDiamond\030\002 \001(\003\022\r\n\005level\030" +
      "\003 \001(\003\022\020\n\010levelStr\030\004 \001(\t\"\256\001\n\nFollowInfo\022\026" +
      "\n\016followingCount\030\001 \001(\004\022\025\n\rfollowerCount\030" +
      "\002 \001(\004\022\024\n\014followStatus\030\003 \001(\004\022\022\n\npushStatu" +
      "s\030\004 \001(\004\022\022\n\nremarkName\030\005 \001(\t\022\030\n\020followerC" +
      "ountStr\030\006 \001(\t\022\031\n\021followingCountStr\030\007 \001(\t" +
      "\"\341\002\n\005Image\022\023\n\013urlListList\030\001 \003(\t\022\013\n\003uri\030\002" +
      " \001(\t\022\016\n\006height\030\003 \001(\004\022\r\n\005width\030\004 \001(\004\022\020\n\010a" +
      "vgColor\030\005 \001(\t\022\021\n\timageType\030\006 \001(\r\022\022\n\nopen" +
      "WebUrl\030\007 \001(\t\022:\n\007content\030\010 \001(\0132).org.exam" +
      "ple.protocol.douyin.ImageContent\022\022\n\nisAn" +
      "imated\030\t \001(\010\022F\n\017FlexSettingList\030\n \001(\0132-." +
      "org.example.protocol.douyin.NinePatchSet" +
      "ting\022F\n\017TextSettingList\030\013 \001(\0132-.org.exam" +
      "ple.protocol.douyin.NinePatchSetting\"+\n\020" +
      "NinePatchSetting\022\027\n\017settingListList\030\001 \003(" +
      "\t\"W\n\014ImageContent\022\014\n\004name\030\001 \001(\t\022\021\n\tfontC" +
      "olor\030\002 \001(\t\022\r\n\005level\030\003 \001(\004\022\027\n\017alternative" +
      "Text\030\004 \001(\t\"\310\001\n\tPushFrame\022\r\n\005seqId\030\001 \001(\004\022" +
      "\r\n\005logId\030\002 \001(\004\022\017\n\007service\030\003 \001(\004\022\016\n\006metho" +
      "d\030\004 \001(\004\022=\n\013headersList\030\005 \003(\0132(.org.examp" +
      "le.protocol.douyin.HeadersList\022\027\n\017payloa" +
      "dEncoding\030\006 \001(\t\022\023\n\013payloadType\030\007 \001(\t\022\017\n\007" +
      "payload\030\010 \001(\014\"\017\n\002kk\022\t\n\001k\030\016 \001(\r\"\342\001\n\017SendM" +
      "essageBody\022\026\n\016conversationId\030\001 \001(\t\022\030\n\020co" +
      "nversationType\030\002 \001(\r\022\033\n\023conversationShor" +
      "tId\030\003 \001(\004\022\017\n\007content\030\004 \001(\t\0221\n\003ext\030\005 \003(\0132" +
      "$.org.example.protocol.douyin.ExtList\022\023\n" +
      "\013messageType\030\006 \001(\r\022\016\n\006ticket\030\007 \001(\t\022\027\n\017cl" +
      "ientMessageId\030\010 \001(\t\"%\n\007ExtList\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\t\"\314\001\n\003Rsp\022\t\n\001a\030\001 \001(\005\022\t\n" +
      "\001b\030\002 \001(\005\022\t\n\001c\030\003 \001(\005\022\t\n\001d\030\004 \001(\t\022\t\n\001e\030\005 \001(" +
      "\005\022-\n\001f\030\006 \001(\0132\".org.example.protocol.douy" +
      "in.Rsp.F\022\t\n\001g\030\007 \001(\t\022\t\n\001h\030\n \001(\004\022\t\n\001i\030\013 \001(" +
      "\004\022\t\n\001j\030\r \001(\004\0323\n\001F\022\n\n\002q1\030\001 \001(\004\022\n\n\002q3\030\003 \001(" +
      "\004\022\n\n\002q4\030\004 \001(\t\022\n\n\002q5\030\005 \001(\004\"\334\002\n\nPreMessage" +
      "\022\013\n\003cmd\030\001 \001(\r\022\022\n\nsequenceId\030\002 \001(\r\022\022\n\nsdk" +
      "Version\030\003 \001(\t\022\r\n\005token\030\004 \001(\t\022\r\n\005refer\030\005 " +
      "\001(\r\022\021\n\tinboxType\030\006 \001(\r\022\023\n\013buildNumber\030\007 " +
      "\001(\t\022E\n\017sendMessageBody\030\010 \001(\0132,.org.examp" +
      "le.protocol.douyin.SendMessageBody\022\n\n\002aa" +
      "\030\t \001(\t\022\026\n\016devicePlatform\030\013 \001(\t\0229\n\007header" +
      "s\030\017 \003(\0132(.org.example.protocol.douyin.He" +
      "adersList\022\020\n\010authType\030\022 \001(\r\022\013\n\003biz\030\025 \001(\t" +
      "\022\016\n\006access\030\026 \001(\t\")\n\013HeadersList\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t\"p\n\023LiveShoppingMessa" +
      "ge\0223\n\006common\030\001 \001(\0132#.org.example.protoco" +
      "l.douyin.Common\022\017\n\007msgType\030\002 \001(\005\022\023\n\013prom" +
      "otionId\030\004 \001(\003\"\202\002\n\020RoomStatsMessage\0223\n\006co" +
      "mmon\030\001 \001(\0132#.org.example.protocol.douyin" +
      ".Common\022\024\n\014displayShort\030\002 \001(\t\022\025\n\rdisplay" +
      "Middle\030\003 \001(\t\022\023\n\013displayLong\030\004 \001(\t\022\024\n\014dis" +
      "playValue\030\005 \001(\003\022\026\n\016displayVersion\030\006 \001(\003\022" +
      "\023\n\013incremental\030\007 \001(\010\022\020\n\010isHidden\030\010 \001(\010\022\r" +
      "\n\005total\030\t \001(\003\022\023\n\013displayType\030\n \001(\003\"c\n\013Pr" +
      "oductInfo\022\023\n\013promotionId\030\001 \001(\003\022\r\n\005index\030" +
      "\002 \001(\005\022\033\n\023targetFlashUidsList\030\003 \003(\003\022\023\n\013ex" +
      "plainType\030\004 \001(\003\"e\n\014CategoryInfo\022\n\n\002id\030\001 " +
      "\001(\005\022\014\n\004name\030\002 \001(\t\022\030\n\020promotionIdsList\030\003 " +
      "\003(\003\022\014\n\004type\030\004 \001(\t\022\023\n\013uniqueIndex\030\005 \001(\t\"\234" +
      "\002\n\024ProductChangeMessage\0223\n\006common\030\001 \001(\0132" +
      "#.org.example.protocol.douyin.Common\022\027\n\017" +
      "updateTimestamp\030\002 \001(\003\022\023\n\013updateToast\030\003 \001" +
      "(\t\022G\n\025updateProductInfoList\030\004 \003(\0132(.org." +
      "example.protocol.douyin.ProductInfo\022\r\n\005t" +
      "otal\030\005 \001(\003\022I\n\026updateCategoryInfoList\030\010 \003" +
      "(\0132).org.example.protocol.douyin.Categor" +
      "yInfo\"U\n\016ControlMessage\0223\n\006common\030\001 \001(\0132" +
      "#.org.example.protocol.douyin.Common\022\016\n\006" +
      "status\030\002 \001(\005\"\232\001\n\017FansclubMessage\0227\n\ncomm" +
      "onInfo\030\001 \001(\0132#.org.example.protocol.douy" +
      "in.Common\022\014\n\004type\030\002 \001(\005\022\017\n\007content\030\003 \001(\t" +
      "\022/\n\004user\030\004 \001(\0132!.org.example.protocol.do",
      "uyin.User\"\366\001\n\017RoomRankMessage\0223\n\006common\030" +
      "\001 \001(\0132#.org.example.protocol.douyin.Comm" +
      "on\022H\n\tranksList\030\002 \003(\01325.org.example.prot" +
      "ocol.douyin.RoomRankMessage.RoomRank\032d\n\010" +
      "RoomRank\022/\n\004user\030\001 \001(\0132!.org.example.pro" +
      "tocol.douyin.User\022\020\n\010scoreStr\030\002 \001(\t\022\025\n\rp" +
      "rofileHidden\030\003 \001(\010\"\202\003\n\013RoomMessage\0223\n\006co" +
      "mmon\030\001 \001(\0132#.org.example.protocol.douyin" +
      ".Common\022\017\n\007content\030\002 \001(\t\022\030\n\020supprotLands" +
      "cape\030\003 \001(\010\022E\n\017roommessagetype\030\004 \001(\0162,.or" +
      "g.example.protocol.douyin.RoomMsgTypeEnu" +
      "m\022\024\n\014systemTopMsg\030\005 \001(\010\022\027\n\017forcedGuarant" +
      "ee\030\006 \001(\010\022\020\n\010bizScene\030\024 \001(\t\022T\n\016buriedPoin" +
      "tMap\030\036 \003(\0132<.org.example.protocol.douyin" +
      ".RoomMessage.BuriedPointMapEntry\0325\n\023Buri" +
      "edPointMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001\"\254\001\n\033RoomStreamAdaptationMessage\022" +
      "3\n\006common\030\001 \001(\0132#.org.example.protocol.d" +
      "ouyin.Common\022\026\n\016adaptationType\030\002 \001(\005\022\035\n\025" +
      "adaptationHeightRatio\030\003 \001(\002\022!\n\031adaptatio" +
      "nBodyCenterRatio\030\004 \001(\002*C\n\016CommentTypeTag" +
      "\022\031\n\025COMMENTTYPETAGUNKNOWN\020\000\022\026\n\022COMMENTTY" +
      "PETAGSTAR\020\001*\335\001\n\017RoomMsgTypeEnum\022\022\n\016DEFAU" +
      "LTROOMMSG\020\000\022\035\n\031ECOMLIVEREPLAYSAVEROOMMSG" +
      "\020\001\022\033\n\027CONSUMERRELATIONROOMMSG\020\002\022\034\n\030JUMAN" +
      "JIDATAAUTHNOTIFYMSG\020\003\022\020\n\014VSWELCOMEMSG\020\004\022" +
      "\022\n\016MINORREFUNDMSG\020\005\022\037\n\033PAIDLIVEROOMNOTIF" +
      "YANCHORMSG\020\006\022\025\n\021HOSTTEAMSYSTEMMSG\020\007B\037\n\033o" +
      "rg.example.protocol.douyinP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_protocol_douyin_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_protocol_douyin_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_Response_descriptor,
        new java.lang.String[] { "MessagesList", "Cursor", "FetchInterval", "Now", "InternalExt", "FetchType", "RouteParams", "HeartbeatDuration", "NeedAck", "PushServer", "LiveCursor", "HistoryNoMore", });
    internal_static_org_example_protocol_douyin_Response_RouteParamsEntry_descriptor =
      internal_static_org_example_protocol_douyin_Response_descriptor.getNestedTypes().get(0);
    internal_static_org_example_protocol_douyin_Response_RouteParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_Response_RouteParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_example_protocol_douyin_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_protocol_douyin_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_Message_descriptor,
        new java.lang.String[] { "Method", "Payload", "MsgId", "MsgType", "Offset", "NeedWrdsStore", "WrdsVersion", "WrdsSubKey", });
    internal_static_org_example_protocol_douyin_EmojiChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_example_protocol_douyin_EmojiChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_EmojiChatMessage_descriptor,
        new java.lang.String[] { "Common", "User", "EmojiId", "EmojiContent", "DefaultContent", "BackgroundImage", "FromIntercom", "IntercomHideUserCard", });
    internal_static_org_example_protocol_douyin_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_example_protocol_douyin_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_ChatMessage_descriptor,
        new java.lang.String[] { "Common", "User", "Content", "VisibleToSender", "BackgroundImage", "FullScreenTextColor", "BackgroundImageV2", "PublicAreaCommon", "GiftImage", "AgreeMsgId", "PriorityLevel", "LandscapeAreaCommon", "EventTime", "SendReview", "FromIntercom", "IntercomHideUserCard", "ChatBy", "IndividualChatPriority", "RtfContent", });
    internal_static_org_example_protocol_douyin_LandscapeAreaCommon_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_example_protocol_douyin_LandscapeAreaCommon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_LandscapeAreaCommon_descriptor,
        new java.lang.String[] { "ShowHead", "ShowNickname", "ShowFontColor", "ColorValueList", "CommentTypeTagsList", });
    internal_static_org_example_protocol_douyin_RoomUserSeqMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_example_protocol_douyin_RoomUserSeqMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_RoomUserSeqMessage_descriptor,
        new java.lang.String[] { "Common", "RanksList", "Total", "PopStr", "SeatsList", "Popularity", "TotalUser", "TotalUserStr", "TotalStr", "OnlineUserForAnchor", "TotalPvForAnchor", "UpRightStatsStr", "UpRightStatsStrComplete", });
    internal_static_org_example_protocol_douyin_CommonTextMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_example_protocol_douyin_CommonTextMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_CommonTextMessage_descriptor,
        new java.lang.String[] { "Common", "User", "Scene", });
    internal_static_org_example_protocol_douyin_UpdateFanTicketMessage_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_org_example_protocol_douyin_UpdateFanTicketMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_UpdateFanTicketMessage_descriptor,
        new java.lang.String[] { "Common", "RoomFanTicketCountText", "RoomFanTicketCount", "ForceUpdate", });
    internal_static_org_example_protocol_douyin_RoomUserSeqMessageContributor_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_org_example_protocol_douyin_RoomUserSeqMessageContributor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_RoomUserSeqMessageContributor_descriptor,
        new java.lang.String[] { "Score", "User", "Rank", "Delta", "IsHidden", "ScoreDescription", "ExactlyScore", });
    internal_static_org_example_protocol_douyin_GiftMessage_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_org_example_protocol_douyin_GiftMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_GiftMessage_descriptor,
        new java.lang.String[] { "Common", "GiftId", "FanTicketCount", "GroupCount", "RepeatCount", "ComboCount", "User", "ToUser", "RepeatEnd", "TextEffect", "GroupId", "IncomeTaskgifts", "RoomFanTicketCount", "Priority", "Gift", "LogId", "SendType", "PublicAreaCommon", "TrayDisplayText", "BannedDisplayEffects", "DisplayForSelf", "InteractGiftInfo", "DiyItemInfo", "MinAssetSetList", "TotalCount", "ClientGiftSource", "ToUserIdsList", "SendTime", "ForceDisplayEffects", "TraceId", "EffectDisplayTs", });
    internal_static_org_example_protocol_douyin_GiftStruct_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_org_example_protocol_douyin_GiftStruct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_GiftStruct_descriptor,
        new java.lang.String[] { "Image", "Describe", "Notify", "Duration", "Id", "ForLinkmic", "Doodle", "ForFansclub", "Combo", "Type", "DiamondCount", "IsDisplayedOnPanel", "PrimaryEffectId", "GiftLabelIcon", "Name", "Region", "Manual", "ForCustom", "Icon", "ActionType", });
    internal_static_org_example_protocol_douyin_GiftIMPriority_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_org_example_protocol_douyin_GiftIMPriority_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_GiftIMPriority_descriptor,
        new java.lang.String[] { "QueueSizesList", "SelfQueuePriority", "Priority", });
    internal_static_org_example_protocol_douyin_TextEffect_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_org_example_protocol_douyin_TextEffect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_TextEffect_descriptor,
        new java.lang.String[] { "Portrait", "Landscape", });
    internal_static_org_example_protocol_douyin_TextEffectDetail_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_org_example_protocol_douyin_TextEffectDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_TextEffectDetail_descriptor,
        new java.lang.String[] { "Text", "TextFontSize", "Background", "Start", "Duration", "X", "Y", "Width", "Height", "ShadowDx", "ShadowDy", "ShadowRadius", "ShadowColor", "StrokeColor", "StrokeWidth", });
    internal_static_org_example_protocol_douyin_MemberMessage_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_org_example_protocol_douyin_MemberMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_MemberMessage_descriptor,
        new java.lang.String[] { "Common", "User", "MemberCount", "Operator", "IsSetToAdmin", "IsTopUser", "RankScore", "TopUserNo", "EnterType", "Action", "ActionDescription", "UserId", "EffectConfig", "PopStr", "EnterEffectConfig", "BackgroundImage", "BackgroundImageV2", "AnchorDisplayText", "PublicAreaCommon", "UserEnterTipType", "AnchorEnterTipType", });
    internal_static_org_example_protocol_douyin_PublicAreaCommon_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_org_example_protocol_douyin_PublicAreaCommon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_PublicAreaCommon_descriptor,
        new java.lang.String[] { "UserLabel", "UserConsumeInRoom", "UserSendGiftCntInRoom", });
    internal_static_org_example_protocol_douyin_EffectConfig_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_org_example_protocol_douyin_EffectConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_EffectConfig_descriptor,
        new java.lang.String[] { "Type", "Icon", "AvatarPos", "Text", "TextIcon", "StayTime", "AnimAssetId", "Badge", "FlexSettingArrayList", "TextIconOverlay", "AnimatedBadge", "HasSweepLight", "TextFlexSettingArrayList", "CenterAnimAssetId", "DynamicImage", "ExtraMap", "Mp4AnimAssetId", "Priority", "MaxWaitTime", "DressId", "Alignment", "AlignmentOffset", });
    internal_static_org_example_protocol_douyin_EffectConfig_ExtraMapEntry_descriptor =
      internal_static_org_example_protocol_douyin_EffectConfig_descriptor.getNestedTypes().get(0);
    internal_static_org_example_protocol_douyin_EffectConfig_ExtraMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_EffectConfig_ExtraMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_example_protocol_douyin_Text_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_org_example_protocol_douyin_Text_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_Text_descriptor,
        new java.lang.String[] { "Key", "DefaultPatter", "DefaultFormat", "PiecesList", });
    internal_static_org_example_protocol_douyin_TextPiece_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_org_example_protocol_douyin_TextPiece_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_TextPiece_descriptor,
        new java.lang.String[] { "Type", "Format", "StringValue", "UserValue", "GiftValue", "HeartValue", "PatternRefValue", "ImageValue", });
    internal_static_org_example_protocol_douyin_TextPieceImage_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_org_example_protocol_douyin_TextPieceImage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_TextPieceImage_descriptor,
        new java.lang.String[] { "Image", "ScalingRate", });
    internal_static_org_example_protocol_douyin_TextPiecePatternRef_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_org_example_protocol_douyin_TextPiecePatternRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_TextPiecePatternRef_descriptor,
        new java.lang.String[] { "Key", "DefaultPattern", });
    internal_static_org_example_protocol_douyin_TextPieceHeart_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_org_example_protocol_douyin_TextPieceHeart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_TextPieceHeart_descriptor,
        new java.lang.String[] { "Color", });
    internal_static_org_example_protocol_douyin_TextPieceGift_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_org_example_protocol_douyin_TextPieceGift_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_TextPieceGift_descriptor,
        new java.lang.String[] { "GiftId", "NameRef", });
    internal_static_org_example_protocol_douyin_PatternRef_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_org_example_protocol_douyin_PatternRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_PatternRef_descriptor,
        new java.lang.String[] { "Key", "DefaultPattern", });
    internal_static_org_example_protocol_douyin_TextPieceUser_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_org_example_protocol_douyin_TextPieceUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_TextPieceUser_descriptor,
        new java.lang.String[] { "User", "WithColon", });
    internal_static_org_example_protocol_douyin_TextFormat_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_org_example_protocol_douyin_TextFormat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_TextFormat_descriptor,
        new java.lang.String[] { "Color", "Bold", "Italic", "Weight", "ItalicAngle", "FontSize", "UseHeighLightColor", "UseRemoteClor", });
    internal_static_org_example_protocol_douyin_LikeMessage_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_org_example_protocol_douyin_LikeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_LikeMessage_descriptor,
        new java.lang.String[] { "Common", "Count", "Total", "Color", "User", "Icon", "DoubleLikeDetail", "DisplayControlInfo", "LinkmicGuestUid", "Scene", "PicoDisplayInfo", });
    internal_static_org_example_protocol_douyin_SocialMessage_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_org_example_protocol_douyin_SocialMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_SocialMessage_descriptor,
        new java.lang.String[] { "Common", "User", "ShareType", "Action", "ShareTarget", "FollowCount", "PublicAreaCommon", });
    internal_static_org_example_protocol_douyin_PicoDisplayInfo_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_org_example_protocol_douyin_PicoDisplayInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_PicoDisplayInfo_descriptor,
        new java.lang.String[] { "ComboSumCount", "Emoji", "EmojiIcon", "EmojiText", });
    internal_static_org_example_protocol_douyin_DoubleLikeDetail_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_org_example_protocol_douyin_DoubleLikeDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_DoubleLikeDetail_descriptor,
        new java.lang.String[] { "DoubleFlag", "SeqId", "RenewalsNum", "TriggersNum", });
    internal_static_org_example_protocol_douyin_DisplayControlInfo_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_org_example_protocol_douyin_DisplayControlInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_DisplayControlInfo_descriptor,
        new java.lang.String[] { "ShowText", "ShowIcons", });
    internal_static_org_example_protocol_douyin_EpisodeChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_org_example_protocol_douyin_EpisodeChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_EpisodeChatMessage_descriptor,
        new java.lang.String[] { "Common", "User", "Content", "VisibleToSende", "GiftImage", "AgreeMsgId", "ColorValueList", });
    internal_static_org_example_protocol_douyin_MatchAgainstScoreMessage_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_org_example_protocol_douyin_MatchAgainstScoreMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_MatchAgainstScoreMessage_descriptor,
        new java.lang.String[] { "Common", "Against", "MatchStatus", "DisplayStatus", });
    internal_static_org_example_protocol_douyin_Against_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_org_example_protocol_douyin_Against_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_Against_descriptor,
        new java.lang.String[] { "LeftName", "LeftLogo", "LeftGoal", "RightName", "RightLogo", "RightGoal", "Timestamp", "Version", "LeftTeamId", "RightTeamId", "DiffSei2AbsSecond", "FinalGoalStage", "CurrentGoalStage", "LeftScoreAddition", "RightScoreAddition", "LeftGoalInt", "RightGoalInt", });
    internal_static_org_example_protocol_douyin_Common_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_org_example_protocol_douyin_Common_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_Common_descriptor,
        new java.lang.String[] { "Method", "MsgId", "RoomId", "CreateTime", "Monitor", "IsShowMsg", "Describe", "FoldType", "AnchorFoldType", "PriorityScore", "LogId", "MsgProcessFilterK", "MsgProcessFilterV", "User", "AnchorFoldTypeV2", "ProcessAtSeiTimeMs", "RandomDispatchMs", "IsDispatch", "ChannelId", "DiffSei2AbsSecond", "AnchorFoldDuration", });
    internal_static_org_example_protocol_douyin_User_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_org_example_protocol_douyin_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_User_descriptor,
        new java.lang.String[] { "Id", "ShortId", "NickName", "Gender", "Signature", "Level", "Birthday", "Telephone", "AvatarThumb", "AvatarMedium", "AvatarLarge", "Verified", "Experience", "City", "Status", "CreateTime", "ModifyTime", "Secret", "ShareQrcodeUri", "IncomeSharePercent", "BadgeImageList", "FollowInfo", "PayGrade", "FansClub", "SpecialId", "AvatarBorder", "Medal", "RealTimeIconsList", "DisplayId", "SecUid", "FanTicketCount", "IdStr", "AgeRange", });
    internal_static_org_example_protocol_douyin_PayGrade_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_org_example_protocol_douyin_PayGrade_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_PayGrade_descriptor,
        new java.lang.String[] { "TotalDiamondCount", "DiamondIcon", "Name", "Icon", "NextName", "Level", "NextIcon", "NextDiamond", "NowDiamond", "ThisGradeMinDiamond", "ThisGradeMaxDiamond", "PayDiamondBak", "GradeDescribe", "GradeIconList", "ScreenChatType", "ImIcon", "ImIconWithLevel", "LiveIcon", "NewImIconWithLevel", "NewLiveIcon", "UpgradeNeedConsume", "NextPrivileges", "Background", "BackgroundBack", "Score", "BuffInfo", "GradeBanner", "ProfileDialogBg", "ProfileDialogBgBack", });
    internal_static_org_example_protocol_douyin_FansClub_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_org_example_protocol_douyin_FansClub_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_FansClub_descriptor,
        new java.lang.String[] { "Data", "PreferData", });
    internal_static_org_example_protocol_douyin_FansClub_PreferDataEntry_descriptor =
      internal_static_org_example_protocol_douyin_FansClub_descriptor.getNestedTypes().get(0);
    internal_static_org_example_protocol_douyin_FansClub_PreferDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_FansClub_PreferDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_example_protocol_douyin_FansClubData_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_org_example_protocol_douyin_FansClubData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_FansClubData_descriptor,
        new java.lang.String[] { "ClubName", "Level", "UserFansClubStatus", "Badge", "AvailableGiftIds", "AnchorId", });
    internal_static_org_example_protocol_douyin_UserBadge_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_org_example_protocol_douyin_UserBadge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_UserBadge_descriptor,
        new java.lang.String[] { "Icons", "Title", });
    internal_static_org_example_protocol_douyin_UserBadge_IconsEntry_descriptor =
      internal_static_org_example_protocol_douyin_UserBadge_descriptor.getNestedTypes().get(0);
    internal_static_org_example_protocol_douyin_UserBadge_IconsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_UserBadge_IconsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_example_protocol_douyin_GradeBuffInfo_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_org_example_protocol_douyin_GradeBuffInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_GradeBuffInfo_descriptor,
        new java.lang.String[] { });
    internal_static_org_example_protocol_douyin_Border_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_org_example_protocol_douyin_Border_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_Border_descriptor,
        new java.lang.String[] { });
    internal_static_org_example_protocol_douyin_GradeIcon_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_org_example_protocol_douyin_GradeIcon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_GradeIcon_descriptor,
        new java.lang.String[] { "Icon", "IconDiamond", "Level", "LevelStr", });
    internal_static_org_example_protocol_douyin_FollowInfo_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_org_example_protocol_douyin_FollowInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_FollowInfo_descriptor,
        new java.lang.String[] { "FollowingCount", "FollowerCount", "FollowStatus", "PushStatus", "RemarkName", "FollowerCountStr", "FollowingCountStr", });
    internal_static_org_example_protocol_douyin_Image_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_org_example_protocol_douyin_Image_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_Image_descriptor,
        new java.lang.String[] { "UrlListList", "Uri", "Height", "Width", "AvgColor", "ImageType", "OpenWebUrl", "Content", "IsAnimated", "FlexSettingList", "TextSettingList", });
    internal_static_org_example_protocol_douyin_NinePatchSetting_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_org_example_protocol_douyin_NinePatchSetting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_NinePatchSetting_descriptor,
        new java.lang.String[] { "SettingListList", });
    internal_static_org_example_protocol_douyin_ImageContent_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_org_example_protocol_douyin_ImageContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_ImageContent_descriptor,
        new java.lang.String[] { "Name", "FontColor", "Level", "AlternativeText", });
    internal_static_org_example_protocol_douyin_PushFrame_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_org_example_protocol_douyin_PushFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_PushFrame_descriptor,
        new java.lang.String[] { "SeqId", "LogId", "Service", "Method", "HeadersList", "PayloadEncoding", "PayloadType", "Payload", });
    internal_static_org_example_protocol_douyin_kk_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_org_example_protocol_douyin_kk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_kk_descriptor,
        new java.lang.String[] { "K", });
    internal_static_org_example_protocol_douyin_SendMessageBody_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_org_example_protocol_douyin_SendMessageBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_SendMessageBody_descriptor,
        new java.lang.String[] { "ConversationId", "ConversationType", "ConversationShortId", "Content", "Ext", "MessageType", "Ticket", "ClientMessageId", });
    internal_static_org_example_protocol_douyin_ExtList_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_org_example_protocol_douyin_ExtList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_ExtList_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_example_protocol_douyin_Rsp_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_org_example_protocol_douyin_Rsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_Rsp_descriptor,
        new java.lang.String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", });
    internal_static_org_example_protocol_douyin_Rsp_F_descriptor =
      internal_static_org_example_protocol_douyin_Rsp_descriptor.getNestedTypes().get(0);
    internal_static_org_example_protocol_douyin_Rsp_F_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_Rsp_F_descriptor,
        new java.lang.String[] { "Q1", "Q3", "Q4", "Q5", });
    internal_static_org_example_protocol_douyin_PreMessage_descriptor =
      getDescriptor().getMessageTypes().get(52);
    internal_static_org_example_protocol_douyin_PreMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_PreMessage_descriptor,
        new java.lang.String[] { "Cmd", "SequenceId", "SdkVersion", "Token", "Refer", "InboxType", "BuildNumber", "SendMessageBody", "Aa", "DevicePlatform", "Headers", "AuthType", "Biz", "Access", });
    internal_static_org_example_protocol_douyin_HeadersList_descriptor =
      getDescriptor().getMessageTypes().get(53);
    internal_static_org_example_protocol_douyin_HeadersList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_HeadersList_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_example_protocol_douyin_LiveShoppingMessage_descriptor =
      getDescriptor().getMessageTypes().get(54);
    internal_static_org_example_protocol_douyin_LiveShoppingMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_LiveShoppingMessage_descriptor,
        new java.lang.String[] { "Common", "MsgType", "PromotionId", });
    internal_static_org_example_protocol_douyin_RoomStatsMessage_descriptor =
      getDescriptor().getMessageTypes().get(55);
    internal_static_org_example_protocol_douyin_RoomStatsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_RoomStatsMessage_descriptor,
        new java.lang.String[] { "Common", "DisplayShort", "DisplayMiddle", "DisplayLong", "DisplayValue", "DisplayVersion", "Incremental", "IsHidden", "Total", "DisplayType", });
    internal_static_org_example_protocol_douyin_ProductInfo_descriptor =
      getDescriptor().getMessageTypes().get(56);
    internal_static_org_example_protocol_douyin_ProductInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_ProductInfo_descriptor,
        new java.lang.String[] { "PromotionId", "Index", "TargetFlashUidsList", "ExplainType", });
    internal_static_org_example_protocol_douyin_CategoryInfo_descriptor =
      getDescriptor().getMessageTypes().get(57);
    internal_static_org_example_protocol_douyin_CategoryInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_CategoryInfo_descriptor,
        new java.lang.String[] { "Id", "Name", "PromotionIdsList", "Type", "UniqueIndex", });
    internal_static_org_example_protocol_douyin_ProductChangeMessage_descriptor =
      getDescriptor().getMessageTypes().get(58);
    internal_static_org_example_protocol_douyin_ProductChangeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_ProductChangeMessage_descriptor,
        new java.lang.String[] { "Common", "UpdateTimestamp", "UpdateToast", "UpdateProductInfoList", "Total", "UpdateCategoryInfoList", });
    internal_static_org_example_protocol_douyin_ControlMessage_descriptor =
      getDescriptor().getMessageTypes().get(59);
    internal_static_org_example_protocol_douyin_ControlMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_ControlMessage_descriptor,
        new java.lang.String[] { "Common", "Status", });
    internal_static_org_example_protocol_douyin_FansclubMessage_descriptor =
      getDescriptor().getMessageTypes().get(60);
    internal_static_org_example_protocol_douyin_FansclubMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_FansclubMessage_descriptor,
        new java.lang.String[] { "CommonInfo", "Type", "Content", "User", });
    internal_static_org_example_protocol_douyin_RoomRankMessage_descriptor =
      getDescriptor().getMessageTypes().get(61);
    internal_static_org_example_protocol_douyin_RoomRankMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_RoomRankMessage_descriptor,
        new java.lang.String[] { "Common", "RanksList", });
    internal_static_org_example_protocol_douyin_RoomRankMessage_RoomRank_descriptor =
      internal_static_org_example_protocol_douyin_RoomRankMessage_descriptor.getNestedTypes().get(0);
    internal_static_org_example_protocol_douyin_RoomRankMessage_RoomRank_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_RoomRankMessage_RoomRank_descriptor,
        new java.lang.String[] { "User", "ScoreStr", "ProfileHidden", });
    internal_static_org_example_protocol_douyin_RoomMessage_descriptor =
      getDescriptor().getMessageTypes().get(62);
    internal_static_org_example_protocol_douyin_RoomMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_RoomMessage_descriptor,
        new java.lang.String[] { "Common", "Content", "SupprotLandscape", "Roommessagetype", "SystemTopMsg", "ForcedGuarantee", "BizScene", "BuriedPointMap", });
    internal_static_org_example_protocol_douyin_RoomMessage_BuriedPointMapEntry_descriptor =
      internal_static_org_example_protocol_douyin_RoomMessage_descriptor.getNestedTypes().get(0);
    internal_static_org_example_protocol_douyin_RoomMessage_BuriedPointMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_RoomMessage_BuriedPointMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_example_protocol_douyin_RoomStreamAdaptationMessage_descriptor =
      getDescriptor().getMessageTypes().get(63);
    internal_static_org_example_protocol_douyin_RoomStreamAdaptationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_protocol_douyin_RoomStreamAdaptationMessage_descriptor,
        new java.lang.String[] { "Common", "AdaptationType", "AdaptationHeightRatio", "AdaptationBodyCenterRatio", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
