// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface EffectConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.EffectConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 type = 1;</code>
   * @return The type.
   */
  long getType();

  /**
   * <code>.org.example.protocol.douyin.Image icon = 2;</code>
   * @return Whether the icon field is set.
   */
  boolean hasIcon();
  /**
   * <code>.org.example.protocol.douyin.Image icon = 2;</code>
   * @return The icon.
   */
  org.example.protocol.douyin.Image getIcon();
  /**
   * <code>.org.example.protocol.douyin.Image icon = 2;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getIconOrBuilder();

  /**
   * <code>uint64 avatarPos = 3;</code>
   * @return The avatarPos.
   */
  long getAvatarPos();

  /**
   * <code>.org.example.protocol.douyin.Text text = 4;</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <code>.org.example.protocol.douyin.Text text = 4;</code>
   * @return The text.
   */
  org.example.protocol.douyin.Text getText();
  /**
   * <code>.org.example.protocol.douyin.Text text = 4;</code>
   */
  org.example.protocol.douyin.TextOrBuilder getTextOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Image textIcon = 5;</code>
   * @return Whether the textIcon field is set.
   */
  boolean hasTextIcon();
  /**
   * <code>.org.example.protocol.douyin.Image textIcon = 5;</code>
   * @return The textIcon.
   */
  org.example.protocol.douyin.Image getTextIcon();
  /**
   * <code>.org.example.protocol.douyin.Image textIcon = 5;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getTextIconOrBuilder();

  /**
   * <code>uint32 stayTime = 6;</code>
   * @return The stayTime.
   */
  int getStayTime();

  /**
   * <code>uint64 animAssetId = 7;</code>
   * @return The animAssetId.
   */
  long getAnimAssetId();

  /**
   * <code>.org.example.protocol.douyin.Image badge = 8;</code>
   * @return Whether the badge field is set.
   */
  boolean hasBadge();
  /**
   * <code>.org.example.protocol.douyin.Image badge = 8;</code>
   * @return The badge.
   */
  org.example.protocol.douyin.Image getBadge();
  /**
   * <code>.org.example.protocol.douyin.Image badge = 8;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getBadgeOrBuilder();

  /**
   * <code>repeated uint64 flexSettingArrayList = 9;</code>
   * @return A list containing the flexSettingArrayList.
   */
  java.util.List<java.lang.Long> getFlexSettingArrayListList();
  /**
   * <code>repeated uint64 flexSettingArrayList = 9;</code>
   * @return The count of flexSettingArrayList.
   */
  int getFlexSettingArrayListCount();
  /**
   * <code>repeated uint64 flexSettingArrayList = 9;</code>
   * @param index The index of the element to return.
   * @return The flexSettingArrayList at the given index.
   */
  long getFlexSettingArrayList(int index);

  /**
   * <code>.org.example.protocol.douyin.Image textIconOverlay = 10;</code>
   * @return Whether the textIconOverlay field is set.
   */
  boolean hasTextIconOverlay();
  /**
   * <code>.org.example.protocol.douyin.Image textIconOverlay = 10;</code>
   * @return The textIconOverlay.
   */
  org.example.protocol.douyin.Image getTextIconOverlay();
  /**
   * <code>.org.example.protocol.douyin.Image textIconOverlay = 10;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getTextIconOverlayOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Image animatedBadge = 11;</code>
   * @return Whether the animatedBadge field is set.
   */
  boolean hasAnimatedBadge();
  /**
   * <code>.org.example.protocol.douyin.Image animatedBadge = 11;</code>
   * @return The animatedBadge.
   */
  org.example.protocol.douyin.Image getAnimatedBadge();
  /**
   * <code>.org.example.protocol.douyin.Image animatedBadge = 11;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getAnimatedBadgeOrBuilder();

  /**
   * <code>bool hasSweepLight = 12;</code>
   * @return The hasSweepLight.
   */
  boolean getHasSweepLight();

  /**
   * <code>repeated uint64 textFlexSettingArrayList = 13;</code>
   * @return A list containing the textFlexSettingArrayList.
   */
  java.util.List<java.lang.Long> getTextFlexSettingArrayListList();
  /**
   * <code>repeated uint64 textFlexSettingArrayList = 13;</code>
   * @return The count of textFlexSettingArrayList.
   */
  int getTextFlexSettingArrayListCount();
  /**
   * <code>repeated uint64 textFlexSettingArrayList = 13;</code>
   * @param index The index of the element to return.
   * @return The textFlexSettingArrayList at the given index.
   */
  long getTextFlexSettingArrayList(int index);

  /**
   * <code>uint64 centerAnimAssetId = 14;</code>
   * @return The centerAnimAssetId.
   */
  long getCenterAnimAssetId();

  /**
   * <code>.org.example.protocol.douyin.Image dynamicImage = 15;</code>
   * @return Whether the dynamicImage field is set.
   */
  boolean hasDynamicImage();
  /**
   * <code>.org.example.protocol.douyin.Image dynamicImage = 15;</code>
   * @return The dynamicImage.
   */
  org.example.protocol.douyin.Image getDynamicImage();
  /**
   * <code>.org.example.protocol.douyin.Image dynamicImage = 15;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getDynamicImageOrBuilder();

  /**
   * <code>map&lt;string, string&gt; extraMap = 16;</code>
   */
  int getExtraMapCount();
  /**
   * <code>map&lt;string, string&gt; extraMap = 16;</code>
   */
  boolean containsExtraMap(
      java.lang.String key);
  /**
   * Use {@link #getExtraMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExtraMap();
  /**
   * <code>map&lt;string, string&gt; extraMap = 16;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExtraMapMap();
  /**
   * <code>map&lt;string, string&gt; extraMap = 16;</code>
   */
  /* nullable */
java.lang.String getExtraMapOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; extraMap = 16;</code>
   */
  java.lang.String getExtraMapOrThrow(
      java.lang.String key);

  /**
   * <code>uint64 mp4AnimAssetId = 17;</code>
   * @return The mp4AnimAssetId.
   */
  long getMp4AnimAssetId();

  /**
   * <code>uint64 priority = 18;</code>
   * @return The priority.
   */
  long getPriority();

  /**
   * <code>uint64 maxWaitTime = 19;</code>
   * @return The maxWaitTime.
   */
  long getMaxWaitTime();

  /**
   * <code>string dressId = 20;</code>
   * @return The dressId.
   */
  java.lang.String getDressId();
  /**
   * <code>string dressId = 20;</code>
   * @return The bytes for dressId.
   */
  com.google.protobuf.ByteString
      getDressIdBytes();

  /**
   * <code>uint64 alignment = 21;</code>
   * @return The alignment.
   */
  long getAlignment();

  /**
   * <code>uint64 alignmentOffset = 22;</code>
   * @return The alignmentOffset.
   */
  long getAlignmentOffset();
}
