// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface EmojiChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.EmojiChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return The common.
   */
  org.example.protocol.douyin.Common getCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   */
  org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.User user = 2;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.org.example.protocol.douyin.User user = 2;</code>
   * @return The user.
   */
  org.example.protocol.douyin.User getUser();
  /**
   * <code>.org.example.protocol.douyin.User user = 2;</code>
   */
  org.example.protocol.douyin.UserOrBuilder getUserOrBuilder();

  /**
   * <code>int64 emojiId = 3;</code>
   * @return The emojiId.
   */
  long getEmojiId();

  /**
   * <code>.org.example.protocol.douyin.Text emojiContent = 4;</code>
   * @return Whether the emojiContent field is set.
   */
  boolean hasEmojiContent();
  /**
   * <code>.org.example.protocol.douyin.Text emojiContent = 4;</code>
   * @return The emojiContent.
   */
  org.example.protocol.douyin.Text getEmojiContent();
  /**
   * <code>.org.example.protocol.douyin.Text emojiContent = 4;</code>
   */
  org.example.protocol.douyin.TextOrBuilder getEmojiContentOrBuilder();

  /**
   * <code>string defaultContent = 5;</code>
   * @return The defaultContent.
   */
  java.lang.String getDefaultContent();
  /**
   * <code>string defaultContent = 5;</code>
   * @return The bytes for defaultContent.
   */
  com.google.protobuf.ByteString
      getDefaultContentBytes();

  /**
   * <code>.org.example.protocol.douyin.Image backgroundImage = 6;</code>
   * @return Whether the backgroundImage field is set.
   */
  boolean hasBackgroundImage();
  /**
   * <code>.org.example.protocol.douyin.Image backgroundImage = 6;</code>
   * @return The backgroundImage.
   */
  org.example.protocol.douyin.Image getBackgroundImage();
  /**
   * <code>.org.example.protocol.douyin.Image backgroundImage = 6;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getBackgroundImageOrBuilder();

  /**
   * <code>bool fromIntercom = 7;</code>
   * @return The fromIntercom.
   */
  boolean getFromIntercom();

  /**
   * <code>bool intercomHideUserCard = 8;</code>
   * @return The intercomHideUserCard.
   */
  boolean getIntercomHideUserCard();
}
