// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface FansClubOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.FansClub)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.FansClubData data = 1;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.org.example.protocol.douyin.FansClubData data = 1;</code>
   * @return The data.
   */
  org.example.protocol.douyin.FansClubData getData();
  /**
   * <code>.org.example.protocol.douyin.FansClubData data = 1;</code>
   */
  org.example.protocol.douyin.FansClubDataOrBuilder getDataOrBuilder();

  /**
   * <code>map&lt;int32, .org.example.protocol.douyin.FansClubData&gt; preferData = 2;</code>
   */
  int getPreferDataCount();
  /**
   * <code>map&lt;int32, .org.example.protocol.douyin.FansClubData&gt; preferData = 2;</code>
   */
  boolean containsPreferData(
      int key);
  /**
   * Use {@link #getPreferDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, org.example.protocol.douyin.FansClubData>
  getPreferData();
  /**
   * <code>map&lt;int32, .org.example.protocol.douyin.FansClubData&gt; preferData = 2;</code>
   */
  java.util.Map<java.lang.Integer, org.example.protocol.douyin.FansClubData>
  getPreferDataMap();
  /**
   * <code>map&lt;int32, .org.example.protocol.douyin.FansClubData&gt; preferData = 2;</code>
   */
  /* nullable */
org.example.protocol.douyin.FansClubData getPreferDataOrDefault(
      int key,
      /* nullable */
org.example.protocol.douyin.FansClubData defaultValue);
  /**
   * <code>map&lt;int32, .org.example.protocol.douyin.FansClubData&gt; preferData = 2;</code>
   */
  org.example.protocol.douyin.FansClubData getPreferDataOrThrow(
      int key);
}
