// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface FansclubMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.FansclubMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Common commonInfo = 1;</code>
   * @return Whether the commonInfo field is set.
   */
  boolean hasCommonInfo();
  /**
   * <code>.org.example.protocol.douyin.Common commonInfo = 1;</code>
   * @return The commonInfo.
   */
  org.example.protocol.douyin.Common getCommonInfo();
  /**
   * <code>.org.example.protocol.douyin.Common commonInfo = 1;</code>
   */
  org.example.protocol.douyin.CommonOrBuilder getCommonInfoOrBuilder();

  /**
   * <pre>
   * 升级是1，加入是2
   * </pre>
   *
   * <code>int32 type = 2;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>.org.example.protocol.douyin.User user = 4;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.org.example.protocol.douyin.User user = 4;</code>
   * @return The user.
   */
  org.example.protocol.douyin.User getUser();
  /**
   * <code>.org.example.protocol.douyin.User user = 4;</code>
   */
  org.example.protocol.douyin.UserOrBuilder getUserOrBuilder();
}
