// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface GiftMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.GiftMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return The common.
   */
  org.example.protocol.douyin.Common getCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   */
  org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>uint64 giftId = 2;</code>
   * @return The giftId.
   */
  long getGiftId();

  /**
   * <code>uint64 fanTicketCount = 3;</code>
   * @return The fanTicketCount.
   */
  long getFanTicketCount();

  /**
   * <code>uint64 groupCount = 4;</code>
   * @return The groupCount.
   */
  long getGroupCount();

  /**
   * <code>uint64 repeatCount = 5;</code>
   * @return The repeatCount.
   */
  long getRepeatCount();

  /**
   * <code>uint64 comboCount = 6;</code>
   * @return The comboCount.
   */
  long getComboCount();

  /**
   * <code>.org.example.protocol.douyin.User user = 7;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.org.example.protocol.douyin.User user = 7;</code>
   * @return The user.
   */
  org.example.protocol.douyin.User getUser();
  /**
   * <code>.org.example.protocol.douyin.User user = 7;</code>
   */
  org.example.protocol.douyin.UserOrBuilder getUserOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.User toUser = 8;</code>
   * @return Whether the toUser field is set.
   */
  boolean hasToUser();
  /**
   * <code>.org.example.protocol.douyin.User toUser = 8;</code>
   * @return The toUser.
   */
  org.example.protocol.douyin.User getToUser();
  /**
   * <code>.org.example.protocol.douyin.User toUser = 8;</code>
   */
  org.example.protocol.douyin.UserOrBuilder getToUserOrBuilder();

  /**
   * <code>uint32 repeatEnd = 9;</code>
   * @return The repeatEnd.
   */
  int getRepeatEnd();

  /**
   * <code>.org.example.protocol.douyin.TextEffect textEffect = 10;</code>
   * @return Whether the textEffect field is set.
   */
  boolean hasTextEffect();
  /**
   * <code>.org.example.protocol.douyin.TextEffect textEffect = 10;</code>
   * @return The textEffect.
   */
  org.example.protocol.douyin.TextEffect getTextEffect();
  /**
   * <code>.org.example.protocol.douyin.TextEffect textEffect = 10;</code>
   */
  org.example.protocol.douyin.TextEffectOrBuilder getTextEffectOrBuilder();

  /**
   * <code>uint64 groupId = 11;</code>
   * @return The groupId.
   */
  long getGroupId();

  /**
   * <code>uint64 incomeTaskgifts = 12;</code>
   * @return The incomeTaskgifts.
   */
  long getIncomeTaskgifts();

  /**
   * <code>uint64 roomFanTicketCount = 13;</code>
   * @return The roomFanTicketCount.
   */
  long getRoomFanTicketCount();

  /**
   * <code>.org.example.protocol.douyin.GiftIMPriority priority = 14;</code>
   * @return Whether the priority field is set.
   */
  boolean hasPriority();
  /**
   * <code>.org.example.protocol.douyin.GiftIMPriority priority = 14;</code>
   * @return The priority.
   */
  org.example.protocol.douyin.GiftIMPriority getPriority();
  /**
   * <code>.org.example.protocol.douyin.GiftIMPriority priority = 14;</code>
   */
  org.example.protocol.douyin.GiftIMPriorityOrBuilder getPriorityOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.GiftStruct gift = 15;</code>
   * @return Whether the gift field is set.
   */
  boolean hasGift();
  /**
   * <code>.org.example.protocol.douyin.GiftStruct gift = 15;</code>
   * @return The gift.
   */
  org.example.protocol.douyin.GiftStruct getGift();
  /**
   * <code>.org.example.protocol.douyin.GiftStruct gift = 15;</code>
   */
  org.example.protocol.douyin.GiftStructOrBuilder getGiftOrBuilder();

  /**
   * <code>string logId = 16;</code>
   * @return The logId.
   */
  java.lang.String getLogId();
  /**
   * <code>string logId = 16;</code>
   * @return The bytes for logId.
   */
  com.google.protobuf.ByteString
      getLogIdBytes();

  /**
   * <code>uint64 sendType = 17;</code>
   * @return The sendType.
   */
  long getSendType();

  /**
   * <code>.org.example.protocol.douyin.PublicAreaCommon publicAreaCommon = 18;</code>
   * @return Whether the publicAreaCommon field is set.
   */
  boolean hasPublicAreaCommon();
  /**
   * <code>.org.example.protocol.douyin.PublicAreaCommon publicAreaCommon = 18;</code>
   * @return The publicAreaCommon.
   */
  org.example.protocol.douyin.PublicAreaCommon getPublicAreaCommon();
  /**
   * <code>.org.example.protocol.douyin.PublicAreaCommon publicAreaCommon = 18;</code>
   */
  org.example.protocol.douyin.PublicAreaCommonOrBuilder getPublicAreaCommonOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Text trayDisplayText = 19;</code>
   * @return Whether the trayDisplayText field is set.
   */
  boolean hasTrayDisplayText();
  /**
   * <code>.org.example.protocol.douyin.Text trayDisplayText = 19;</code>
   * @return The trayDisplayText.
   */
  org.example.protocol.douyin.Text getTrayDisplayText();
  /**
   * <code>.org.example.protocol.douyin.Text trayDisplayText = 19;</code>
   */
  org.example.protocol.douyin.TextOrBuilder getTrayDisplayTextOrBuilder();

  /**
   * <code>uint64 bannedDisplayEffects = 20;</code>
   * @return The bannedDisplayEffects.
   */
  long getBannedDisplayEffects();

  /**
   * <pre>
   *  GiftTrayInfo trayInfo = 21;
   *  AssetEffectMixInfo assetEffectMixInfo = 22;
   * </pre>
   *
   * <code>bool displayForSelf = 25;</code>
   * @return The displayForSelf.
   */
  boolean getDisplayForSelf();

  /**
   * <code>string interactGiftInfo = 26;</code>
   * @return The interactGiftInfo.
   */
  java.lang.String getInteractGiftInfo();
  /**
   * <code>string interactGiftInfo = 26;</code>
   * @return The bytes for interactGiftInfo.
   */
  com.google.protobuf.ByteString
      getInteractGiftInfoBytes();

  /**
   * <code>string diyItemInfo = 27;</code>
   * @return The diyItemInfo.
   */
  java.lang.String getDiyItemInfo();
  /**
   * <code>string diyItemInfo = 27;</code>
   * @return The bytes for diyItemInfo.
   */
  com.google.protobuf.ByteString
      getDiyItemInfoBytes();

  /**
   * <code>repeated uint64 minAssetSetList = 28;</code>
   * @return A list containing the minAssetSetList.
   */
  java.util.List<java.lang.Long> getMinAssetSetListList();
  /**
   * <code>repeated uint64 minAssetSetList = 28;</code>
   * @return The count of minAssetSetList.
   */
  int getMinAssetSetListCount();
  /**
   * <code>repeated uint64 minAssetSetList = 28;</code>
   * @param index The index of the element to return.
   * @return The minAssetSetList at the given index.
   */
  long getMinAssetSetList(int index);

  /**
   * <code>uint64 totalCount = 29;</code>
   * @return The totalCount.
   */
  long getTotalCount();

  /**
   * <code>uint32 clientGiftSource = 30;</code>
   * @return The clientGiftSource.
   */
  int getClientGiftSource();

  /**
   * <pre>
   *  AnchorGiftData anchorGift = 31;
   * </pre>
   *
   * <code>repeated uint64 toUserIdsList = 32;</code>
   * @return A list containing the toUserIdsList.
   */
  java.util.List<java.lang.Long> getToUserIdsListList();
  /**
   * <pre>
   *  AnchorGiftData anchorGift = 31;
   * </pre>
   *
   * <code>repeated uint64 toUserIdsList = 32;</code>
   * @return The count of toUserIdsList.
   */
  int getToUserIdsListCount();
  /**
   * <pre>
   *  AnchorGiftData anchorGift = 31;
   * </pre>
   *
   * <code>repeated uint64 toUserIdsList = 32;</code>
   * @param index The index of the element to return.
   * @return The toUserIdsList at the given index.
   */
  long getToUserIdsList(int index);

  /**
   * <code>uint64 sendTime = 33;</code>
   * @return The sendTime.
   */
  long getSendTime();

  /**
   * <code>uint64 forceDisplayEffects = 34;</code>
   * @return The forceDisplayEffects.
   */
  long getForceDisplayEffects();

  /**
   * <code>string traceId = 35;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <code>string traceId = 35;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <code>uint64 effectDisplayTs = 36;</code>
   * @return The effectDisplayTs.
   */
  long getEffectDisplayTs();
}
