// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface GradeIconOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.GradeIcon)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Image icon = 1;</code>
   * @return Whether the icon field is set.
   */
  boolean hasIcon();
  /**
   * <code>.org.example.protocol.douyin.Image icon = 1;</code>
   * @return The icon.
   */
  org.example.protocol.douyin.Image getIcon();
  /**
   * <code>.org.example.protocol.douyin.Image icon = 1;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getIconOrBuilder();

  /**
   * <code>int64 iconDiamond = 2;</code>
   * @return The iconDiamond.
   */
  long getIconDiamond();

  /**
   * <code>int64 level = 3;</code>
   * @return The level.
   */
  long getLevel();

  /**
   * <code>string levelStr = 4;</code>
   * @return The levelStr.
   */
  java.lang.String getLevelStr();
  /**
   * <code>string levelStr = 4;</code>
   * @return The bytes for levelStr.
   */
  com.google.protobuf.ByteString
      getLevelStrBytes();
}
