// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface kkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.kk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 k = 14;</code>
   * @return The k.
   */
  int getK();
}
