// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface LikeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.LikeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return The common.
   */
  org.example.protocol.douyin.Common getCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   */
  org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>uint64 count = 2;</code>
   * @return The count.
   */
  long getCount();

  /**
   * <code>uint64 total = 3;</code>
   * @return The total.
   */
  long getTotal();

  /**
   * <code>uint64 color = 4;</code>
   * @return The color.
   */
  long getColor();

  /**
   * <code>.org.example.protocol.douyin.User user = 5;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.org.example.protocol.douyin.User user = 5;</code>
   * @return The user.
   */
  org.example.protocol.douyin.User getUser();
  /**
   * <code>.org.example.protocol.douyin.User user = 5;</code>
   */
  org.example.protocol.douyin.UserOrBuilder getUserOrBuilder();

  /**
   * <code>string icon = 6;</code>
   * @return The icon.
   */
  java.lang.String getIcon();
  /**
   * <code>string icon = 6;</code>
   * @return The bytes for icon.
   */
  com.google.protobuf.ByteString
      getIconBytes();

  /**
   * <code>.org.example.protocol.douyin.DoubleLikeDetail doubleLikeDetail = 7;</code>
   * @return Whether the doubleLikeDetail field is set.
   */
  boolean hasDoubleLikeDetail();
  /**
   * <code>.org.example.protocol.douyin.DoubleLikeDetail doubleLikeDetail = 7;</code>
   * @return The doubleLikeDetail.
   */
  org.example.protocol.douyin.DoubleLikeDetail getDoubleLikeDetail();
  /**
   * <code>.org.example.protocol.douyin.DoubleLikeDetail doubleLikeDetail = 7;</code>
   */
  org.example.protocol.douyin.DoubleLikeDetailOrBuilder getDoubleLikeDetailOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.DisplayControlInfo displayControlInfo = 8;</code>
   * @return Whether the displayControlInfo field is set.
   */
  boolean hasDisplayControlInfo();
  /**
   * <code>.org.example.protocol.douyin.DisplayControlInfo displayControlInfo = 8;</code>
   * @return The displayControlInfo.
   */
  org.example.protocol.douyin.DisplayControlInfo getDisplayControlInfo();
  /**
   * <code>.org.example.protocol.douyin.DisplayControlInfo displayControlInfo = 8;</code>
   */
  org.example.protocol.douyin.DisplayControlInfoOrBuilder getDisplayControlInfoOrBuilder();

  /**
   * <code>uint64 linkmicGuestUid = 9;</code>
   * @return The linkmicGuestUid.
   */
  long getLinkmicGuestUid();

  /**
   * <code>string scene = 10;</code>
   * @return The scene.
   */
  java.lang.String getScene();
  /**
   * <code>string scene = 10;</code>
   * @return The bytes for scene.
   */
  com.google.protobuf.ByteString
      getSceneBytes();

  /**
   * <code>.org.example.protocol.douyin.PicoDisplayInfo picoDisplayInfo = 11;</code>
   * @return Whether the picoDisplayInfo field is set.
   */
  boolean hasPicoDisplayInfo();
  /**
   * <code>.org.example.protocol.douyin.PicoDisplayInfo picoDisplayInfo = 11;</code>
   * @return The picoDisplayInfo.
   */
  org.example.protocol.douyin.PicoDisplayInfo getPicoDisplayInfo();
  /**
   * <code>.org.example.protocol.douyin.PicoDisplayInfo picoDisplayInfo = 11;</code>
   */
  org.example.protocol.douyin.PicoDisplayInfoOrBuilder getPicoDisplayInfoOrBuilder();
}
