// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface LiveShoppingMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.LiveShoppingMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return The common.
   */
  org.example.protocol.douyin.Common getCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   */
  org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>int32 msgType = 2;</code>
   * @return The msgType.
   */
  int getMsgType();

  /**
   * <code>int64 promotionId = 4;</code>
   * @return The promotionId.
   */
  long getPromotionId();
}
