// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface MatchAgainstScoreMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.MatchAgainstScoreMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return The common.
   */
  org.example.protocol.douyin.Common getCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   */
  org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Against against = 2;</code>
   * @return Whether the against field is set.
   */
  boolean hasAgainst();
  /**
   * <code>.org.example.protocol.douyin.Against against = 2;</code>
   * @return The against.
   */
  org.example.protocol.douyin.Against getAgainst();
  /**
   * <code>.org.example.protocol.douyin.Against against = 2;</code>
   */
  org.example.protocol.douyin.AgainstOrBuilder getAgainstOrBuilder();

  /**
   * <code>uint32 matchStatus = 3;</code>
   * @return The matchStatus.
   */
  int getMatchStatus();

  /**
   * <code>uint32 displayStatus = 4;</code>
   * @return The displayStatus.
   */
  int getDisplayStatus();
}
