// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface MemberMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.MemberMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return The common.
   */
  org.example.protocol.douyin.Common getCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   */
  org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.User user = 2;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.org.example.protocol.douyin.User user = 2;</code>
   * @return The user.
   */
  org.example.protocol.douyin.User getUser();
  /**
   * <code>.org.example.protocol.douyin.User user = 2;</code>
   */
  org.example.protocol.douyin.UserOrBuilder getUserOrBuilder();

  /**
   * <code>uint64 memberCount = 3;</code>
   * @return The memberCount.
   */
  long getMemberCount();

  /**
   * <code>.org.example.protocol.douyin.User operator = 4;</code>
   * @return Whether the operator field is set.
   */
  boolean hasOperator();
  /**
   * <code>.org.example.protocol.douyin.User operator = 4;</code>
   * @return The operator.
   */
  org.example.protocol.douyin.User getOperator();
  /**
   * <code>.org.example.protocol.douyin.User operator = 4;</code>
   */
  org.example.protocol.douyin.UserOrBuilder getOperatorOrBuilder();

  /**
   * <code>bool isSetToAdmin = 5;</code>
   * @return The isSetToAdmin.
   */
  boolean getIsSetToAdmin();

  /**
   * <code>bool isTopUser = 6;</code>
   * @return The isTopUser.
   */
  boolean getIsTopUser();

  /**
   * <code>uint64 rankScore = 7;</code>
   * @return The rankScore.
   */
  long getRankScore();

  /**
   * <code>uint64 topUserNo = 8;</code>
   * @return The topUserNo.
   */
  long getTopUserNo();

  /**
   * <code>uint64 enterType = 9;</code>
   * @return The enterType.
   */
  long getEnterType();

  /**
   * <code>uint64 action = 10;</code>
   * @return The action.
   */
  long getAction();

  /**
   * <code>string actionDescription = 11;</code>
   * @return The actionDescription.
   */
  java.lang.String getActionDescription();
  /**
   * <code>string actionDescription = 11;</code>
   * @return The bytes for actionDescription.
   */
  com.google.protobuf.ByteString
      getActionDescriptionBytes();

  /**
   * <code>uint64 userId = 12;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>.org.example.protocol.douyin.EffectConfig effectConfig = 13;</code>
   * @return Whether the effectConfig field is set.
   */
  boolean hasEffectConfig();
  /**
   * <code>.org.example.protocol.douyin.EffectConfig effectConfig = 13;</code>
   * @return The effectConfig.
   */
  org.example.protocol.douyin.EffectConfig getEffectConfig();
  /**
   * <code>.org.example.protocol.douyin.EffectConfig effectConfig = 13;</code>
   */
  org.example.protocol.douyin.EffectConfigOrBuilder getEffectConfigOrBuilder();

  /**
   * <code>string popStr = 14;</code>
   * @return The popStr.
   */
  java.lang.String getPopStr();
  /**
   * <code>string popStr = 14;</code>
   * @return The bytes for popStr.
   */
  com.google.protobuf.ByteString
      getPopStrBytes();

  /**
   * <code>.org.example.protocol.douyin.EffectConfig enterEffectConfig = 15;</code>
   * @return Whether the enterEffectConfig field is set.
   */
  boolean hasEnterEffectConfig();
  /**
   * <code>.org.example.protocol.douyin.EffectConfig enterEffectConfig = 15;</code>
   * @return The enterEffectConfig.
   */
  org.example.protocol.douyin.EffectConfig getEnterEffectConfig();
  /**
   * <code>.org.example.protocol.douyin.EffectConfig enterEffectConfig = 15;</code>
   */
  org.example.protocol.douyin.EffectConfigOrBuilder getEnterEffectConfigOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Image backgroundImage = 16;</code>
   * @return Whether the backgroundImage field is set.
   */
  boolean hasBackgroundImage();
  /**
   * <code>.org.example.protocol.douyin.Image backgroundImage = 16;</code>
   * @return The backgroundImage.
   */
  org.example.protocol.douyin.Image getBackgroundImage();
  /**
   * <code>.org.example.protocol.douyin.Image backgroundImage = 16;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getBackgroundImageOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Image backgroundImageV2 = 17;</code>
   * @return Whether the backgroundImageV2 field is set.
   */
  boolean hasBackgroundImageV2();
  /**
   * <code>.org.example.protocol.douyin.Image backgroundImageV2 = 17;</code>
   * @return The backgroundImageV2.
   */
  org.example.protocol.douyin.Image getBackgroundImageV2();
  /**
   * <code>.org.example.protocol.douyin.Image backgroundImageV2 = 17;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getBackgroundImageV2OrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Text anchorDisplayText = 18;</code>
   * @return Whether the anchorDisplayText field is set.
   */
  boolean hasAnchorDisplayText();
  /**
   * <code>.org.example.protocol.douyin.Text anchorDisplayText = 18;</code>
   * @return The anchorDisplayText.
   */
  org.example.protocol.douyin.Text getAnchorDisplayText();
  /**
   * <code>.org.example.protocol.douyin.Text anchorDisplayText = 18;</code>
   */
  org.example.protocol.douyin.TextOrBuilder getAnchorDisplayTextOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.PublicAreaCommon publicAreaCommon = 19;</code>
   * @return Whether the publicAreaCommon field is set.
   */
  boolean hasPublicAreaCommon();
  /**
   * <code>.org.example.protocol.douyin.PublicAreaCommon publicAreaCommon = 19;</code>
   * @return The publicAreaCommon.
   */
  org.example.protocol.douyin.PublicAreaCommon getPublicAreaCommon();
  /**
   * <code>.org.example.protocol.douyin.PublicAreaCommon publicAreaCommon = 19;</code>
   */
  org.example.protocol.douyin.PublicAreaCommonOrBuilder getPublicAreaCommonOrBuilder();

  /**
   * <code>uint64 userEnterTipType = 20;</code>
   * @return The userEnterTipType.
   */
  long getUserEnterTipType();

  /**
   * <code>uint64 anchorEnterTipType = 21;</code>
   * @return The anchorEnterTipType.
   */
  long getAnchorEnterTipType();
}
