// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface PatternRefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.PatternRef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string defaultPattern = 2;</code>
   * @return The defaultPattern.
   */
  java.lang.String getDefaultPattern();
  /**
   * <code>string defaultPattern = 2;</code>
   * @return The bytes for defaultPattern.
   */
  com.google.protobuf.ByteString
      getDefaultPatternBytes();
}
