// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface PayGradeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.PayGrade)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 totalDiamondCount = 1;</code>
   * @return The totalDiamondCount.
   */
  long getTotalDiamondCount();

  /**
   * <code>.org.example.protocol.douyin.Image diamondIcon = 2;</code>
   * @return Whether the diamondIcon field is set.
   */
  boolean hasDiamondIcon();
  /**
   * <code>.org.example.protocol.douyin.Image diamondIcon = 2;</code>
   * @return The diamondIcon.
   */
  org.example.protocol.douyin.Image getDiamondIcon();
  /**
   * <code>.org.example.protocol.douyin.Image diamondIcon = 2;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getDiamondIconOrBuilder();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.org.example.protocol.douyin.Image icon = 4;</code>
   * @return Whether the icon field is set.
   */
  boolean hasIcon();
  /**
   * <code>.org.example.protocol.douyin.Image icon = 4;</code>
   * @return The icon.
   */
  org.example.protocol.douyin.Image getIcon();
  /**
   * <code>.org.example.protocol.douyin.Image icon = 4;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getIconOrBuilder();

  /**
   * <code>string nextName = 5;</code>
   * @return The nextName.
   */
  java.lang.String getNextName();
  /**
   * <code>string nextName = 5;</code>
   * @return The bytes for nextName.
   */
  com.google.protobuf.ByteString
      getNextNameBytes();

  /**
   * <code>int64 level = 6;</code>
   * @return The level.
   */
  long getLevel();

  /**
   * <code>.org.example.protocol.douyin.Image nextIcon = 7;</code>
   * @return Whether the nextIcon field is set.
   */
  boolean hasNextIcon();
  /**
   * <code>.org.example.protocol.douyin.Image nextIcon = 7;</code>
   * @return The nextIcon.
   */
  org.example.protocol.douyin.Image getNextIcon();
  /**
   * <code>.org.example.protocol.douyin.Image nextIcon = 7;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getNextIconOrBuilder();

  /**
   * <code>int64 nextDiamond = 8;</code>
   * @return The nextDiamond.
   */
  long getNextDiamond();

  /**
   * <code>int64 nowDiamond = 9;</code>
   * @return The nowDiamond.
   */
  long getNowDiamond();

  /**
   * <code>int64 thisGradeMinDiamond = 10;</code>
   * @return The thisGradeMinDiamond.
   */
  long getThisGradeMinDiamond();

  /**
   * <code>int64 thisGradeMaxDiamond = 11;</code>
   * @return The thisGradeMaxDiamond.
   */
  long getThisGradeMaxDiamond();

  /**
   * <code>int64 payDiamondBak = 12;</code>
   * @return The payDiamondBak.
   */
  long getPayDiamondBak();

  /**
   * <code>string gradeDescribe = 13;</code>
   * @return The gradeDescribe.
   */
  java.lang.String getGradeDescribe();
  /**
   * <code>string gradeDescribe = 13;</code>
   * @return The bytes for gradeDescribe.
   */
  com.google.protobuf.ByteString
      getGradeDescribeBytes();

  /**
   * <code>repeated .org.example.protocol.douyin.GradeIcon gradeIconList = 14;</code>
   */
  java.util.List<org.example.protocol.douyin.GradeIcon> 
      getGradeIconListList();
  /**
   * <code>repeated .org.example.protocol.douyin.GradeIcon gradeIconList = 14;</code>
   */
  org.example.protocol.douyin.GradeIcon getGradeIconList(int index);
  /**
   * <code>repeated .org.example.protocol.douyin.GradeIcon gradeIconList = 14;</code>
   */
  int getGradeIconListCount();
  /**
   * <code>repeated .org.example.protocol.douyin.GradeIcon gradeIconList = 14;</code>
   */
  java.util.List<? extends org.example.protocol.douyin.GradeIconOrBuilder> 
      getGradeIconListOrBuilderList();
  /**
   * <code>repeated .org.example.protocol.douyin.GradeIcon gradeIconList = 14;</code>
   */
  org.example.protocol.douyin.GradeIconOrBuilder getGradeIconListOrBuilder(
      int index);

  /**
   * <code>int64 screenChatType = 15;</code>
   * @return The screenChatType.
   */
  long getScreenChatType();

  /**
   * <code>.org.example.protocol.douyin.Image imIcon = 16;</code>
   * @return Whether the imIcon field is set.
   */
  boolean hasImIcon();
  /**
   * <code>.org.example.protocol.douyin.Image imIcon = 16;</code>
   * @return The imIcon.
   */
  org.example.protocol.douyin.Image getImIcon();
  /**
   * <code>.org.example.protocol.douyin.Image imIcon = 16;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getImIconOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Image imIconWithLevel = 17;</code>
   * @return Whether the imIconWithLevel field is set.
   */
  boolean hasImIconWithLevel();
  /**
   * <code>.org.example.protocol.douyin.Image imIconWithLevel = 17;</code>
   * @return The imIconWithLevel.
   */
  org.example.protocol.douyin.Image getImIconWithLevel();
  /**
   * <code>.org.example.protocol.douyin.Image imIconWithLevel = 17;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getImIconWithLevelOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Image liveIcon = 18;</code>
   * @return Whether the liveIcon field is set.
   */
  boolean hasLiveIcon();
  /**
   * <code>.org.example.protocol.douyin.Image liveIcon = 18;</code>
   * @return The liveIcon.
   */
  org.example.protocol.douyin.Image getLiveIcon();
  /**
   * <code>.org.example.protocol.douyin.Image liveIcon = 18;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getLiveIconOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Image newImIconWithLevel = 19;</code>
   * @return Whether the newImIconWithLevel field is set.
   */
  boolean hasNewImIconWithLevel();
  /**
   * <code>.org.example.protocol.douyin.Image newImIconWithLevel = 19;</code>
   * @return The newImIconWithLevel.
   */
  org.example.protocol.douyin.Image getNewImIconWithLevel();
  /**
   * <code>.org.example.protocol.douyin.Image newImIconWithLevel = 19;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getNewImIconWithLevelOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Image newLiveIcon = 20;</code>
   * @return Whether the newLiveIcon field is set.
   */
  boolean hasNewLiveIcon();
  /**
   * <code>.org.example.protocol.douyin.Image newLiveIcon = 20;</code>
   * @return The newLiveIcon.
   */
  org.example.protocol.douyin.Image getNewLiveIcon();
  /**
   * <code>.org.example.protocol.douyin.Image newLiveIcon = 20;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getNewLiveIconOrBuilder();

  /**
   * <code>int64 upgradeNeedConsume = 21;</code>
   * @return The upgradeNeedConsume.
   */
  long getUpgradeNeedConsume();

  /**
   * <code>string nextPrivileges = 22;</code>
   * @return The nextPrivileges.
   */
  java.lang.String getNextPrivileges();
  /**
   * <code>string nextPrivileges = 22;</code>
   * @return The bytes for nextPrivileges.
   */
  com.google.protobuf.ByteString
      getNextPrivilegesBytes();

  /**
   * <code>.org.example.protocol.douyin.Image background = 23;</code>
   * @return Whether the background field is set.
   */
  boolean hasBackground();
  /**
   * <code>.org.example.protocol.douyin.Image background = 23;</code>
   * @return The background.
   */
  org.example.protocol.douyin.Image getBackground();
  /**
   * <code>.org.example.protocol.douyin.Image background = 23;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getBackgroundOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Image backgroundBack = 24;</code>
   * @return Whether the backgroundBack field is set.
   */
  boolean hasBackgroundBack();
  /**
   * <code>.org.example.protocol.douyin.Image backgroundBack = 24;</code>
   * @return The backgroundBack.
   */
  org.example.protocol.douyin.Image getBackgroundBack();
  /**
   * <code>.org.example.protocol.douyin.Image backgroundBack = 24;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getBackgroundBackOrBuilder();

  /**
   * <code>int64 score = 25;</code>
   * @return The score.
   */
  long getScore();

  /**
   * <code>.org.example.protocol.douyin.GradeBuffInfo buffInfo = 26;</code>
   * @return Whether the buffInfo field is set.
   */
  boolean hasBuffInfo();
  /**
   * <code>.org.example.protocol.douyin.GradeBuffInfo buffInfo = 26;</code>
   * @return The buffInfo.
   */
  org.example.protocol.douyin.GradeBuffInfo getBuffInfo();
  /**
   * <code>.org.example.protocol.douyin.GradeBuffInfo buffInfo = 26;</code>
   */
  org.example.protocol.douyin.GradeBuffInfoOrBuilder getBuffInfoOrBuilder();

  /**
   * <code>string gradeBanner = 1001;</code>
   * @return The gradeBanner.
   */
  java.lang.String getGradeBanner();
  /**
   * <code>string gradeBanner = 1001;</code>
   * @return The bytes for gradeBanner.
   */
  com.google.protobuf.ByteString
      getGradeBannerBytes();

  /**
   * <code>.org.example.protocol.douyin.Image profileDialogBg = 1002;</code>
   * @return Whether the profileDialogBg field is set.
   */
  boolean hasProfileDialogBg();
  /**
   * <code>.org.example.protocol.douyin.Image profileDialogBg = 1002;</code>
   * @return The profileDialogBg.
   */
  org.example.protocol.douyin.Image getProfileDialogBg();
  /**
   * <code>.org.example.protocol.douyin.Image profileDialogBg = 1002;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getProfileDialogBgOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Image profileDialogBgBack = 1003;</code>
   * @return Whether the profileDialogBgBack field is set.
   */
  boolean hasProfileDialogBgBack();
  /**
   * <code>.org.example.protocol.douyin.Image profileDialogBgBack = 1003;</code>
   * @return The profileDialogBgBack.
   */
  org.example.protocol.douyin.Image getProfileDialogBgBack();
  /**
   * <code>.org.example.protocol.douyin.Image profileDialogBgBack = 1003;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getProfileDialogBgBackOrBuilder();
}
