// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface PreMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.PreMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 cmd = 1;</code>
   * @return The cmd.
   */
  int getCmd();

  /**
   * <code>uint32 sequenceId = 2;</code>
   * @return The sequenceId.
   */
  int getSequenceId();

  /**
   * <code>string sdkVersion = 3;</code>
   * @return The sdkVersion.
   */
  java.lang.String getSdkVersion();
  /**
   * <code>string sdkVersion = 3;</code>
   * @return The bytes for sdkVersion.
   */
  com.google.protobuf.ByteString
      getSdkVersionBytes();

  /**
   * <code>string token = 4;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 4;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>uint32 refer = 5;</code>
   * @return The refer.
   */
  int getRefer();

  /**
   * <code>uint32 inboxType = 6;</code>
   * @return The inboxType.
   */
  int getInboxType();

  /**
   * <code>string buildNumber = 7;</code>
   * @return The buildNumber.
   */
  java.lang.String getBuildNumber();
  /**
   * <code>string buildNumber = 7;</code>
   * @return The bytes for buildNumber.
   */
  com.google.protobuf.ByteString
      getBuildNumberBytes();

  /**
   * <code>.org.example.protocol.douyin.SendMessageBody sendMessageBody = 8;</code>
   * @return Whether the sendMessageBody field is set.
   */
  boolean hasSendMessageBody();
  /**
   * <code>.org.example.protocol.douyin.SendMessageBody sendMessageBody = 8;</code>
   * @return The sendMessageBody.
   */
  org.example.protocol.douyin.SendMessageBody getSendMessageBody();
  /**
   * <code>.org.example.protocol.douyin.SendMessageBody sendMessageBody = 8;</code>
   */
  org.example.protocol.douyin.SendMessageBodyOrBuilder getSendMessageBodyOrBuilder();

  /**
   * <pre>
   * 字段名待定
   * </pre>
   *
   * <code>string aa = 9;</code>
   * @return The aa.
   */
  java.lang.String getAa();
  /**
   * <pre>
   * 字段名待定
   * </pre>
   *
   * <code>string aa = 9;</code>
   * @return The bytes for aa.
   */
  com.google.protobuf.ByteString
      getAaBytes();

  /**
   * <code>string devicePlatform = 11;</code>
   * @return The devicePlatform.
   */
  java.lang.String getDevicePlatform();
  /**
   * <code>string devicePlatform = 11;</code>
   * @return The bytes for devicePlatform.
   */
  com.google.protobuf.ByteString
      getDevicePlatformBytes();

  /**
   * <code>repeated .org.example.protocol.douyin.HeadersList headers = 15;</code>
   */
  java.util.List<org.example.protocol.douyin.HeadersList> 
      getHeadersList();
  /**
   * <code>repeated .org.example.protocol.douyin.HeadersList headers = 15;</code>
   */
  org.example.protocol.douyin.HeadersList getHeaders(int index);
  /**
   * <code>repeated .org.example.protocol.douyin.HeadersList headers = 15;</code>
   */
  int getHeadersCount();
  /**
   * <code>repeated .org.example.protocol.douyin.HeadersList headers = 15;</code>
   */
  java.util.List<? extends org.example.protocol.douyin.HeadersListOrBuilder> 
      getHeadersOrBuilderList();
  /**
   * <code>repeated .org.example.protocol.douyin.HeadersList headers = 15;</code>
   */
  org.example.protocol.douyin.HeadersListOrBuilder getHeadersOrBuilder(
      int index);

  /**
   * <code>uint32 authType = 18;</code>
   * @return The authType.
   */
  int getAuthType();

  /**
   * <code>string biz = 21;</code>
   * @return The biz.
   */
  java.lang.String getBiz();
  /**
   * <code>string biz = 21;</code>
   * @return The bytes for biz.
   */
  com.google.protobuf.ByteString
      getBizBytes();

  /**
   * <code>string access = 22;</code>
   * @return The access.
   */
  java.lang.String getAccess();
  /**
   * <code>string access = 22;</code>
   * @return The bytes for access.
   */
  com.google.protobuf.ByteString
      getAccessBytes();
}
