// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface ProductChangeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.ProductChangeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return The common.
   */
  org.example.protocol.douyin.Common getCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   */
  org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>int64 updateTimestamp = 2;</code>
   * @return The updateTimestamp.
   */
  long getUpdateTimestamp();

  /**
   * <code>string updateToast = 3;</code>
   * @return The updateToast.
   */
  java.lang.String getUpdateToast();
  /**
   * <code>string updateToast = 3;</code>
   * @return The bytes for updateToast.
   */
  com.google.protobuf.ByteString
      getUpdateToastBytes();

  /**
   * <code>repeated .org.example.protocol.douyin.ProductInfo updateProductInfoList = 4;</code>
   */
  java.util.List<org.example.protocol.douyin.ProductInfo> 
      getUpdateProductInfoListList();
  /**
   * <code>repeated .org.example.protocol.douyin.ProductInfo updateProductInfoList = 4;</code>
   */
  org.example.protocol.douyin.ProductInfo getUpdateProductInfoList(int index);
  /**
   * <code>repeated .org.example.protocol.douyin.ProductInfo updateProductInfoList = 4;</code>
   */
  int getUpdateProductInfoListCount();
  /**
   * <code>repeated .org.example.protocol.douyin.ProductInfo updateProductInfoList = 4;</code>
   */
  java.util.List<? extends org.example.protocol.douyin.ProductInfoOrBuilder> 
      getUpdateProductInfoListOrBuilderList();
  /**
   * <code>repeated .org.example.protocol.douyin.ProductInfo updateProductInfoList = 4;</code>
   */
  org.example.protocol.douyin.ProductInfoOrBuilder getUpdateProductInfoListOrBuilder(
      int index);

  /**
   * <code>int64 total = 5;</code>
   * @return The total.
   */
  long getTotal();

  /**
   * <code>repeated .org.example.protocol.douyin.CategoryInfo updateCategoryInfoList = 8;</code>
   */
  java.util.List<org.example.protocol.douyin.CategoryInfo> 
      getUpdateCategoryInfoListList();
  /**
   * <code>repeated .org.example.protocol.douyin.CategoryInfo updateCategoryInfoList = 8;</code>
   */
  org.example.protocol.douyin.CategoryInfo getUpdateCategoryInfoList(int index);
  /**
   * <code>repeated .org.example.protocol.douyin.CategoryInfo updateCategoryInfoList = 8;</code>
   */
  int getUpdateCategoryInfoListCount();
  /**
   * <code>repeated .org.example.protocol.douyin.CategoryInfo updateCategoryInfoList = 8;</code>
   */
  java.util.List<? extends org.example.protocol.douyin.CategoryInfoOrBuilder> 
      getUpdateCategoryInfoListOrBuilderList();
  /**
   * <code>repeated .org.example.protocol.douyin.CategoryInfo updateCategoryInfoList = 8;</code>
   */
  org.example.protocol.douyin.CategoryInfoOrBuilder getUpdateCategoryInfoListOrBuilder(
      int index);
}
