// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface PublicAreaCommonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.PublicAreaCommon)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Image userLabel = 1;</code>
   * @return Whether the userLabel field is set.
   */
  boolean hasUserLabel();
  /**
   * <code>.org.example.protocol.douyin.Image userLabel = 1;</code>
   * @return The userLabel.
   */
  org.example.protocol.douyin.Image getUserLabel();
  /**
   * <code>.org.example.protocol.douyin.Image userLabel = 1;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getUserLabelOrBuilder();

  /**
   * <code>uint64 userConsumeInRoom = 2;</code>
   * @return The userConsumeInRoom.
   */
  long getUserConsumeInRoom();

  /**
   * <code>uint64 userSendGiftCntInRoom = 3;</code>
   * @return The userSendGiftCntInRoom.
   */
  long getUserSendGiftCntInRoom();
}
