// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.example.protocol.douyin.Message messagesList = 1;</code>
   */
  java.util.List<org.example.protocol.douyin.Message> 
      getMessagesListList();
  /**
   * <code>repeated .org.example.protocol.douyin.Message messagesList = 1;</code>
   */
  org.example.protocol.douyin.Message getMessagesList(int index);
  /**
   * <code>repeated .org.example.protocol.douyin.Message messagesList = 1;</code>
   */
  int getMessagesListCount();
  /**
   * <code>repeated .org.example.protocol.douyin.Message messagesList = 1;</code>
   */
  java.util.List<? extends org.example.protocol.douyin.MessageOrBuilder> 
      getMessagesListOrBuilderList();
  /**
   * <code>repeated .org.example.protocol.douyin.Message messagesList = 1;</code>
   */
  org.example.protocol.douyin.MessageOrBuilder getMessagesListOrBuilder(
      int index);

  /**
   * <code>string cursor = 2;</code>
   * @return The cursor.
   */
  java.lang.String getCursor();
  /**
   * <code>string cursor = 2;</code>
   * @return The bytes for cursor.
   */
  com.google.protobuf.ByteString
      getCursorBytes();

  /**
   * <code>uint64 fetchInterval = 3;</code>
   * @return The fetchInterval.
   */
  long getFetchInterval();

  /**
   * <code>uint64 now = 4;</code>
   * @return The now.
   */
  long getNow();

  /**
   * <code>string internalExt = 5;</code>
   * @return The internalExt.
   */
  java.lang.String getInternalExt();
  /**
   * <code>string internalExt = 5;</code>
   * @return The bytes for internalExt.
   */
  com.google.protobuf.ByteString
      getInternalExtBytes();

  /**
   * <code>uint32 fetchType = 6;</code>
   * @return The fetchType.
   */
  int getFetchType();

  /**
   * <code>map&lt;string, string&gt; routeParams = 7;</code>
   */
  int getRouteParamsCount();
  /**
   * <code>map&lt;string, string&gt; routeParams = 7;</code>
   */
  boolean containsRouteParams(
      java.lang.String key);
  /**
   * Use {@link #getRouteParamsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getRouteParams();
  /**
   * <code>map&lt;string, string&gt; routeParams = 7;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getRouteParamsMap();
  /**
   * <code>map&lt;string, string&gt; routeParams = 7;</code>
   */
  /* nullable */
java.lang.String getRouteParamsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; routeParams = 7;</code>
   */
  java.lang.String getRouteParamsOrThrow(
      java.lang.String key);

  /**
   * <code>uint64 heartbeatDuration = 8;</code>
   * @return The heartbeatDuration.
   */
  long getHeartbeatDuration();

  /**
   * <code>bool needAck = 9;</code>
   * @return The needAck.
   */
  boolean getNeedAck();

  /**
   * <code>string pushServer = 10;</code>
   * @return The pushServer.
   */
  java.lang.String getPushServer();
  /**
   * <code>string pushServer = 10;</code>
   * @return The bytes for pushServer.
   */
  com.google.protobuf.ByteString
      getPushServerBytes();

  /**
   * <code>string liveCursor = 11;</code>
   * @return The liveCursor.
   */
  java.lang.String getLiveCursor();
  /**
   * <code>string liveCursor = 11;</code>
   * @return The bytes for liveCursor.
   */
  com.google.protobuf.ByteString
      getLiveCursorBytes();

  /**
   * <code>bool historyNoMore = 12;</code>
   * @return The historyNoMore.
   */
  boolean getHistoryNoMore();
}
