// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface RoomStreamAdaptationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.RoomStreamAdaptationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return The common.
   */
  org.example.protocol.douyin.Common getCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   */
  org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>int32 adaptationType = 2;</code>
   * @return The adaptationType.
   */
  int getAdaptationType();

  /**
   * <code>float adaptationHeightRatio = 3;</code>
   * @return The adaptationHeightRatio.
   */
  float getAdaptationHeightRatio();

  /**
   * <code>float adaptationBodyCenterRatio = 4;</code>
   * @return The adaptationBodyCenterRatio.
   */
  float getAdaptationBodyCenterRatio();
}
