// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

/**
 * <pre>
 * from https://github.com/jwwsjlm/douyinLive/tree/main/protobuf/douyin.proto
 * </pre>
 *
 * Protobuf type {@code org.example.protocol.douyin.RoomStreamAdaptationMessage}
 */
public final class RoomStreamAdaptationMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.example.protocol.douyin.RoomStreamAdaptationMessage)
    RoomStreamAdaptationMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RoomStreamAdaptationMessage.newBuilder() to construct.
  private RoomStreamAdaptationMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RoomStreamAdaptationMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RoomStreamAdaptationMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.protocol.douyin.Douyin.internal_static_org_example_protocol_douyin_RoomStreamAdaptationMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.protocol.douyin.Douyin.internal_static_org_example_protocol_douyin_RoomStreamAdaptationMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.protocol.douyin.RoomStreamAdaptationMessage.class, org.example.protocol.douyin.RoomStreamAdaptationMessage.Builder.class);
  }

  private int bitField0_;
  public static final int COMMON_FIELD_NUMBER = 1;
  private org.example.protocol.douyin.Common common_;
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  @java.lang.Override
  public boolean hasCommon() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return The common.
   */
  @java.lang.Override
  public org.example.protocol.douyin.Common getCommon() {
    return common_ == null ? org.example.protocol.douyin.Common.getDefaultInstance() : common_;
  }
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   */
  @java.lang.Override
  public org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder() {
    return common_ == null ? org.example.protocol.douyin.Common.getDefaultInstance() : common_;
  }

  public static final int ADAPTATIONTYPE_FIELD_NUMBER = 2;
  private int adaptationType_ = 0;
  /**
   * <code>int32 adaptationType = 2;</code>
   * @return The adaptationType.
   */
  @java.lang.Override
  public int getAdaptationType() {
    return adaptationType_;
  }

  public static final int ADAPTATIONHEIGHTRATIO_FIELD_NUMBER = 3;
  private float adaptationHeightRatio_ = 0F;
  /**
   * <code>float adaptationHeightRatio = 3;</code>
   * @return The adaptationHeightRatio.
   */
  @java.lang.Override
  public float getAdaptationHeightRatio() {
    return adaptationHeightRatio_;
  }

  public static final int ADAPTATIONBODYCENTERRATIO_FIELD_NUMBER = 4;
  private float adaptationBodyCenterRatio_ = 0F;
  /**
   * <code>float adaptationBodyCenterRatio = 4;</code>
   * @return The adaptationBodyCenterRatio.
   */
  @java.lang.Override
  public float getAdaptationBodyCenterRatio() {
    return adaptationBodyCenterRatio_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCommon());
    }
    if (adaptationType_ != 0) {
      output.writeInt32(2, adaptationType_);
    }
    if (java.lang.Float.floatToRawIntBits(adaptationHeightRatio_) != 0) {
      output.writeFloat(3, adaptationHeightRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(adaptationBodyCenterRatio_) != 0) {
      output.writeFloat(4, adaptationBodyCenterRatio_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCommon());
    }
    if (adaptationType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, adaptationType_);
    }
    if (java.lang.Float.floatToRawIntBits(adaptationHeightRatio_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, adaptationHeightRatio_);
    }
    if (java.lang.Float.floatToRawIntBits(adaptationBodyCenterRatio_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, adaptationBodyCenterRatio_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.protocol.douyin.RoomStreamAdaptationMessage)) {
      return super.equals(obj);
    }
    org.example.protocol.douyin.RoomStreamAdaptationMessage other = (org.example.protocol.douyin.RoomStreamAdaptationMessage) obj;

    if (hasCommon() != other.hasCommon()) return false;
    if (hasCommon()) {
      if (!getCommon()
          .equals(other.getCommon())) return false;
    }
    if (getAdaptationType()
        != other.getAdaptationType()) return false;
    if (java.lang.Float.floatToIntBits(getAdaptationHeightRatio())
        != java.lang.Float.floatToIntBits(
            other.getAdaptationHeightRatio())) return false;
    if (java.lang.Float.floatToIntBits(getAdaptationBodyCenterRatio())
        != java.lang.Float.floatToIntBits(
            other.getAdaptationBodyCenterRatio())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCommon()) {
      hash = (37 * hash) + COMMON_FIELD_NUMBER;
      hash = (53 * hash) + getCommon().hashCode();
    }
    hash = (37 * hash) + ADAPTATIONTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getAdaptationType();
    hash = (37 * hash) + ADAPTATIONHEIGHTRATIO_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAdaptationHeightRatio());
    hash = (37 * hash) + ADAPTATIONBODYCENTERRATIO_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAdaptationBodyCenterRatio());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.protocol.douyin.RoomStreamAdaptationMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protocol.douyin.RoomStreamAdaptationMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protocol.douyin.RoomStreamAdaptationMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protocol.douyin.RoomStreamAdaptationMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protocol.douyin.RoomStreamAdaptationMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protocol.douyin.RoomStreamAdaptationMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protocol.douyin.RoomStreamAdaptationMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.protocol.douyin.RoomStreamAdaptationMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.protocol.douyin.RoomStreamAdaptationMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.protocol.douyin.RoomStreamAdaptationMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.protocol.douyin.RoomStreamAdaptationMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.protocol.douyin.RoomStreamAdaptationMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.protocol.douyin.RoomStreamAdaptationMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * from https://github.com/jwwsjlm/douyinLive/tree/main/protobuf/douyin.proto
   * </pre>
   *
   * Protobuf type {@code org.example.protocol.douyin.RoomStreamAdaptationMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.example.protocol.douyin.RoomStreamAdaptationMessage)
      org.example.protocol.douyin.RoomStreamAdaptationMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.protocol.douyin.Douyin.internal_static_org_example_protocol_douyin_RoomStreamAdaptationMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.protocol.douyin.Douyin.internal_static_org_example_protocol_douyin_RoomStreamAdaptationMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.protocol.douyin.RoomStreamAdaptationMessage.class, org.example.protocol.douyin.RoomStreamAdaptationMessage.Builder.class);
    }

    // Construct using org.example.protocol.douyin.RoomStreamAdaptationMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCommonFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      common_ = null;
      if (commonBuilder_ != null) {
        commonBuilder_.dispose();
        commonBuilder_ = null;
      }
      adaptationType_ = 0;
      adaptationHeightRatio_ = 0F;
      adaptationBodyCenterRatio_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.protocol.douyin.Douyin.internal_static_org_example_protocol_douyin_RoomStreamAdaptationMessage_descriptor;
    }

    @java.lang.Override
    public org.example.protocol.douyin.RoomStreamAdaptationMessage getDefaultInstanceForType() {
      return org.example.protocol.douyin.RoomStreamAdaptationMessage.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.protocol.douyin.RoomStreamAdaptationMessage build() {
      org.example.protocol.douyin.RoomStreamAdaptationMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.protocol.douyin.RoomStreamAdaptationMessage buildPartial() {
      org.example.protocol.douyin.RoomStreamAdaptationMessage result = new org.example.protocol.douyin.RoomStreamAdaptationMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.protocol.douyin.RoomStreamAdaptationMessage result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.common_ = commonBuilder_ == null
            ? common_
            : commonBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.adaptationType_ = adaptationType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.adaptationHeightRatio_ = adaptationHeightRatio_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.adaptationBodyCenterRatio_ = adaptationBodyCenterRatio_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.protocol.douyin.RoomStreamAdaptationMessage) {
        return mergeFrom((org.example.protocol.douyin.RoomStreamAdaptationMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.protocol.douyin.RoomStreamAdaptationMessage other) {
      if (other == org.example.protocol.douyin.RoomStreamAdaptationMessage.getDefaultInstance()) return this;
      if (other.hasCommon()) {
        mergeCommon(other.getCommon());
      }
      if (other.getAdaptationType() != 0) {
        setAdaptationType(other.getAdaptationType());
      }
      if (other.getAdaptationHeightRatio() != 0F) {
        setAdaptationHeightRatio(other.getAdaptationHeightRatio());
      }
      if (other.getAdaptationBodyCenterRatio() != 0F) {
        setAdaptationBodyCenterRatio(other.getAdaptationBodyCenterRatio());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCommonFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              adaptationType_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 29: {
              adaptationHeightRatio_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 37: {
              adaptationBodyCenterRatio_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.example.protocol.douyin.Common common_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.example.protocol.douyin.Common, org.example.protocol.douyin.Common.Builder, org.example.protocol.douyin.CommonOrBuilder> commonBuilder_;
    /**
     * <code>.org.example.protocol.douyin.Common common = 1;</code>
     * @return Whether the common field is set.
     */
    public boolean hasCommon() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.org.example.protocol.douyin.Common common = 1;</code>
     * @return The common.
     */
    public org.example.protocol.douyin.Common getCommon() {
      if (commonBuilder_ == null) {
        return common_ == null ? org.example.protocol.douyin.Common.getDefaultInstance() : common_;
      } else {
        return commonBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.example.protocol.douyin.Common common = 1;</code>
     */
    public Builder setCommon(org.example.protocol.douyin.Common value) {
      if (commonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        common_ = value;
      } else {
        commonBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.org.example.protocol.douyin.Common common = 1;</code>
     */
    public Builder setCommon(
        org.example.protocol.douyin.Common.Builder builderForValue) {
      if (commonBuilder_ == null) {
        common_ = builderForValue.build();
      } else {
        commonBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.org.example.protocol.douyin.Common common = 1;</code>
     */
    public Builder mergeCommon(org.example.protocol.douyin.Common value) {
      if (commonBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          common_ != null &&
          common_ != org.example.protocol.douyin.Common.getDefaultInstance()) {
          getCommonBuilder().mergeFrom(value);
        } else {
          common_ = value;
        }
      } else {
        commonBuilder_.mergeFrom(value);
      }
      if (common_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.org.example.protocol.douyin.Common common = 1;</code>
     */
    public Builder clearCommon() {
      bitField0_ = (bitField0_ & ~0x00000001);
      common_ = null;
      if (commonBuilder_ != null) {
        commonBuilder_.dispose();
        commonBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.org.example.protocol.douyin.Common common = 1;</code>
     */
    public org.example.protocol.douyin.Common.Builder getCommonBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCommonFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.example.protocol.douyin.Common common = 1;</code>
     */
    public org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder() {
      if (commonBuilder_ != null) {
        return commonBuilder_.getMessageOrBuilder();
      } else {
        return common_ == null ?
            org.example.protocol.douyin.Common.getDefaultInstance() : common_;
      }
    }
    /**
     * <code>.org.example.protocol.douyin.Common common = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.example.protocol.douyin.Common, org.example.protocol.douyin.Common.Builder, org.example.protocol.douyin.CommonOrBuilder> 
        getCommonFieldBuilder() {
      if (commonBuilder_ == null) {
        commonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.example.protocol.douyin.Common, org.example.protocol.douyin.Common.Builder, org.example.protocol.douyin.CommonOrBuilder>(
                getCommon(),
                getParentForChildren(),
                isClean());
        common_ = null;
      }
      return commonBuilder_;
    }

    private int adaptationType_ ;
    /**
     * <code>int32 adaptationType = 2;</code>
     * @return The adaptationType.
     */
    @java.lang.Override
    public int getAdaptationType() {
      return adaptationType_;
    }
    /**
     * <code>int32 adaptationType = 2;</code>
     * @param value The adaptationType to set.
     * @return This builder for chaining.
     */
    public Builder setAdaptationType(int value) {

      adaptationType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 adaptationType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdaptationType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      adaptationType_ = 0;
      onChanged();
      return this;
    }

    private float adaptationHeightRatio_ ;
    /**
     * <code>float adaptationHeightRatio = 3;</code>
     * @return The adaptationHeightRatio.
     */
    @java.lang.Override
    public float getAdaptationHeightRatio() {
      return adaptationHeightRatio_;
    }
    /**
     * <code>float adaptationHeightRatio = 3;</code>
     * @param value The adaptationHeightRatio to set.
     * @return This builder for chaining.
     */
    public Builder setAdaptationHeightRatio(float value) {

      adaptationHeightRatio_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float adaptationHeightRatio = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdaptationHeightRatio() {
      bitField0_ = (bitField0_ & ~0x00000004);
      adaptationHeightRatio_ = 0F;
      onChanged();
      return this;
    }

    private float adaptationBodyCenterRatio_ ;
    /**
     * <code>float adaptationBodyCenterRatio = 4;</code>
     * @return The adaptationBodyCenterRatio.
     */
    @java.lang.Override
    public float getAdaptationBodyCenterRatio() {
      return adaptationBodyCenterRatio_;
    }
    /**
     * <code>float adaptationBodyCenterRatio = 4;</code>
     * @param value The adaptationBodyCenterRatio to set.
     * @return This builder for chaining.
     */
    public Builder setAdaptationBodyCenterRatio(float value) {

      adaptationBodyCenterRatio_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>float adaptationBodyCenterRatio = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdaptationBodyCenterRatio() {
      bitField0_ = (bitField0_ & ~0x00000008);
      adaptationBodyCenterRatio_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.example.protocol.douyin.RoomStreamAdaptationMessage)
  }

  // @@protoc_insertion_point(class_scope:org.example.protocol.douyin.RoomStreamAdaptationMessage)
  private static final org.example.protocol.douyin.RoomStreamAdaptationMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.protocol.douyin.RoomStreamAdaptationMessage();
  }

  public static org.example.protocol.douyin.RoomStreamAdaptationMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RoomStreamAdaptationMessage>
      PARSER = new com.google.protobuf.AbstractParser<RoomStreamAdaptationMessage>() {
    @java.lang.Override
    public RoomStreamAdaptationMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RoomStreamAdaptationMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RoomStreamAdaptationMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.protocol.douyin.RoomStreamAdaptationMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

