// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface RoomMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.RoomMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return The common.
   */
  org.example.protocol.douyin.Common getCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   */
  org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>bool supprotLandscape = 3;</code>
   * @return The supprotLandscape.
   */
  boolean getSupprotLandscape();

  /**
   * <code>.org.example.protocol.douyin.RoomMsgTypeEnum roommessagetype = 4;</code>
   * @return The enum numeric value on the wire for roommessagetype.
   */
  int getRoommessagetypeValue();
  /**
   * <code>.org.example.protocol.douyin.RoomMsgTypeEnum roommessagetype = 4;</code>
   * @return The roommessagetype.
   */
  org.example.protocol.douyin.RoomMsgTypeEnum getRoommessagetype();

  /**
   * <code>bool systemTopMsg = 5;</code>
   * @return The systemTopMsg.
   */
  boolean getSystemTopMsg();

  /**
   * <code>bool forcedGuarantee = 6;</code>
   * @return The forcedGuarantee.
   */
  boolean getForcedGuarantee();

  /**
   * <code>string bizScene = 20;</code>
   * @return The bizScene.
   */
  java.lang.String getBizScene();
  /**
   * <code>string bizScene = 20;</code>
   * @return The bytes for bizScene.
   */
  com.google.protobuf.ByteString
      getBizSceneBytes();

  /**
   * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
   */
  int getBuriedPointMapCount();
  /**
   * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
   */
  boolean containsBuriedPointMap(
      java.lang.String key);
  /**
   * Use {@link #getBuriedPointMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getBuriedPointMap();
  /**
   * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getBuriedPointMapMap();
  /**
   * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
   */
  /* nullable */
java.lang.String getBuriedPointMapOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; buriedPointMap = 30;</code>
   */
  java.lang.String getBuriedPointMapOrThrow(
      java.lang.String key);
}
