// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface RoomUserSeqMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.RoomUserSeqMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return The common.
   */
  org.example.protocol.douyin.Common getCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   */
  org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>repeated .org.example.protocol.douyin.RoomUserSeqMessageContributor ranksList = 2;</code>
   */
  java.util.List<org.example.protocol.douyin.RoomUserSeqMessageContributor> 
      getRanksListList();
  /**
   * <code>repeated .org.example.protocol.douyin.RoomUserSeqMessageContributor ranksList = 2;</code>
   */
  org.example.protocol.douyin.RoomUserSeqMessageContributor getRanksList(int index);
  /**
   * <code>repeated .org.example.protocol.douyin.RoomUserSeqMessageContributor ranksList = 2;</code>
   */
  int getRanksListCount();
  /**
   * <code>repeated .org.example.protocol.douyin.RoomUserSeqMessageContributor ranksList = 2;</code>
   */
  java.util.List<? extends org.example.protocol.douyin.RoomUserSeqMessageContributorOrBuilder> 
      getRanksListOrBuilderList();
  /**
   * <code>repeated .org.example.protocol.douyin.RoomUserSeqMessageContributor ranksList = 2;</code>
   */
  org.example.protocol.douyin.RoomUserSeqMessageContributorOrBuilder getRanksListOrBuilder(
      int index);

  /**
   * <code>int64 total = 3;</code>
   * @return The total.
   */
  long getTotal();

  /**
   * <code>string popStr = 4;</code>
   * @return The popStr.
   */
  java.lang.String getPopStr();
  /**
   * <code>string popStr = 4;</code>
   * @return The bytes for popStr.
   */
  com.google.protobuf.ByteString
      getPopStrBytes();

  /**
   * <code>repeated .org.example.protocol.douyin.RoomUserSeqMessageContributor seatsList = 5;</code>
   */
  java.util.List<org.example.protocol.douyin.RoomUserSeqMessageContributor> 
      getSeatsListList();
  /**
   * <code>repeated .org.example.protocol.douyin.RoomUserSeqMessageContributor seatsList = 5;</code>
   */
  org.example.protocol.douyin.RoomUserSeqMessageContributor getSeatsList(int index);
  /**
   * <code>repeated .org.example.protocol.douyin.RoomUserSeqMessageContributor seatsList = 5;</code>
   */
  int getSeatsListCount();
  /**
   * <code>repeated .org.example.protocol.douyin.RoomUserSeqMessageContributor seatsList = 5;</code>
   */
  java.util.List<? extends org.example.protocol.douyin.RoomUserSeqMessageContributorOrBuilder> 
      getSeatsListOrBuilderList();
  /**
   * <code>repeated .org.example.protocol.douyin.RoomUserSeqMessageContributor seatsList = 5;</code>
   */
  org.example.protocol.douyin.RoomUserSeqMessageContributorOrBuilder getSeatsListOrBuilder(
      int index);

  /**
   * <code>int64 popularity = 6;</code>
   * @return The popularity.
   */
  long getPopularity();

  /**
   * <code>int64 totalUser = 7;</code>
   * @return The totalUser.
   */
  long getTotalUser();

  /**
   * <code>string totalUserStr = 8;</code>
   * @return The totalUserStr.
   */
  java.lang.String getTotalUserStr();
  /**
   * <code>string totalUserStr = 8;</code>
   * @return The bytes for totalUserStr.
   */
  com.google.protobuf.ByteString
      getTotalUserStrBytes();

  /**
   * <code>string totalStr = 9;</code>
   * @return The totalStr.
   */
  java.lang.String getTotalStr();
  /**
   * <code>string totalStr = 9;</code>
   * @return The bytes for totalStr.
   */
  com.google.protobuf.ByteString
      getTotalStrBytes();

  /**
   * <code>string onlineUserForAnchor = 10;</code>
   * @return The onlineUserForAnchor.
   */
  java.lang.String getOnlineUserForAnchor();
  /**
   * <code>string onlineUserForAnchor = 10;</code>
   * @return The bytes for onlineUserForAnchor.
   */
  com.google.protobuf.ByteString
      getOnlineUserForAnchorBytes();

  /**
   * <code>string totalPvForAnchor = 11;</code>
   * @return The totalPvForAnchor.
   */
  java.lang.String getTotalPvForAnchor();
  /**
   * <code>string totalPvForAnchor = 11;</code>
   * @return The bytes for totalPvForAnchor.
   */
  com.google.protobuf.ByteString
      getTotalPvForAnchorBytes();

  /**
   * <code>string upRightStatsStr = 12;</code>
   * @return The upRightStatsStr.
   */
  java.lang.String getUpRightStatsStr();
  /**
   * <code>string upRightStatsStr = 12;</code>
   * @return The bytes for upRightStatsStr.
   */
  com.google.protobuf.ByteString
      getUpRightStatsStrBytes();

  /**
   * <code>string upRightStatsStrComplete = 13;</code>
   * @return The upRightStatsStrComplete.
   */
  java.lang.String getUpRightStatsStrComplete();
  /**
   * <code>string upRightStatsStrComplete = 13;</code>
   * @return The bytes for upRightStatsStrComplete.
   */
  com.google.protobuf.ByteString
      getUpRightStatsStrCompleteBytes();
}
