// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface SocialMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.SocialMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return The common.
   */
  org.example.protocol.douyin.Common getCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   */
  org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.User user = 2;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.org.example.protocol.douyin.User user = 2;</code>
   * @return The user.
   */
  org.example.protocol.douyin.User getUser();
  /**
   * <code>.org.example.protocol.douyin.User user = 2;</code>
   */
  org.example.protocol.douyin.UserOrBuilder getUserOrBuilder();

  /**
   * <code>uint64 shareType = 3;</code>
   * @return The shareType.
   */
  long getShareType();

  /**
   * <code>uint64 action = 4;</code>
   * @return The action.
   */
  long getAction();

  /**
   * <code>string shareTarget = 5;</code>
   * @return The shareTarget.
   */
  java.lang.String getShareTarget();
  /**
   * <code>string shareTarget = 5;</code>
   * @return The bytes for shareTarget.
   */
  com.google.protobuf.ByteString
      getShareTargetBytes();

  /**
   * <code>uint64 followCount = 6;</code>
   * @return The followCount.
   */
  long getFollowCount();

  /**
   * <code>.org.example.protocol.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
   * @return Whether the publicAreaCommon field is set.
   */
  boolean hasPublicAreaCommon();
  /**
   * <code>.org.example.protocol.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
   * @return The publicAreaCommon.
   */
  org.example.protocol.douyin.PublicAreaCommon getPublicAreaCommon();
  /**
   * <code>.org.example.protocol.douyin.PublicAreaCommon publicAreaCommon = 7;</code>
   */
  org.example.protocol.douyin.PublicAreaCommonOrBuilder getPublicAreaCommonOrBuilder();
}
