// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface TextPieceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.TextPiece)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool type = 1;</code>
   * @return The type.
   */
  boolean getType();

  /**
   * <code>.org.example.protocol.douyin.TextFormat format = 2;</code>
   * @return Whether the format field is set.
   */
  boolean hasFormat();
  /**
   * <code>.org.example.protocol.douyin.TextFormat format = 2;</code>
   * @return The format.
   */
  org.example.protocol.douyin.TextFormat getFormat();
  /**
   * <code>.org.example.protocol.douyin.TextFormat format = 2;</code>
   */
  org.example.protocol.douyin.TextFormatOrBuilder getFormatOrBuilder();

  /**
   * <code>string stringValue = 3;</code>
   * @return The stringValue.
   */
  java.lang.String getStringValue();
  /**
   * <code>string stringValue = 3;</code>
   * @return The bytes for stringValue.
   */
  com.google.protobuf.ByteString
      getStringValueBytes();

  /**
   * <code>.org.example.protocol.douyin.TextPieceUser userValue = 4;</code>
   * @return Whether the userValue field is set.
   */
  boolean hasUserValue();
  /**
   * <code>.org.example.protocol.douyin.TextPieceUser userValue = 4;</code>
   * @return The userValue.
   */
  org.example.protocol.douyin.TextPieceUser getUserValue();
  /**
   * <code>.org.example.protocol.douyin.TextPieceUser userValue = 4;</code>
   */
  org.example.protocol.douyin.TextPieceUserOrBuilder getUserValueOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.TextPieceGift giftValue = 5;</code>
   * @return Whether the giftValue field is set.
   */
  boolean hasGiftValue();
  /**
   * <code>.org.example.protocol.douyin.TextPieceGift giftValue = 5;</code>
   * @return The giftValue.
   */
  org.example.protocol.douyin.TextPieceGift getGiftValue();
  /**
   * <code>.org.example.protocol.douyin.TextPieceGift giftValue = 5;</code>
   */
  org.example.protocol.douyin.TextPieceGiftOrBuilder getGiftValueOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.TextPieceHeart heartValue = 6;</code>
   * @return Whether the heartValue field is set.
   */
  boolean hasHeartValue();
  /**
   * <code>.org.example.protocol.douyin.TextPieceHeart heartValue = 6;</code>
   * @return The heartValue.
   */
  org.example.protocol.douyin.TextPieceHeart getHeartValue();
  /**
   * <code>.org.example.protocol.douyin.TextPieceHeart heartValue = 6;</code>
   */
  org.example.protocol.douyin.TextPieceHeartOrBuilder getHeartValueOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.TextPiecePatternRef patternRefValue = 7;</code>
   * @return Whether the patternRefValue field is set.
   */
  boolean hasPatternRefValue();
  /**
   * <code>.org.example.protocol.douyin.TextPiecePatternRef patternRefValue = 7;</code>
   * @return The patternRefValue.
   */
  org.example.protocol.douyin.TextPiecePatternRef getPatternRefValue();
  /**
   * <code>.org.example.protocol.douyin.TextPiecePatternRef patternRefValue = 7;</code>
   */
  org.example.protocol.douyin.TextPiecePatternRefOrBuilder getPatternRefValueOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.TextPieceImage imageValue = 8;</code>
   * @return Whether the imageValue field is set.
   */
  boolean hasImageValue();
  /**
   * <code>.org.example.protocol.douyin.TextPieceImage imageValue = 8;</code>
   * @return The imageValue.
   */
  org.example.protocol.douyin.TextPieceImage getImageValue();
  /**
   * <code>.org.example.protocol.douyin.TextPieceImage imageValue = 8;</code>
   */
  org.example.protocol.douyin.TextPieceImageOrBuilder getImageValueOrBuilder();
}
