// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface TextPieceGiftOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.TextPieceGift)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 giftId = 1;</code>
   * @return The giftId.
   */
  long getGiftId();

  /**
   * <code>.org.example.protocol.douyin.PatternRef nameRef = 2;</code>
   * @return Whether the nameRef field is set.
   */
  boolean hasNameRef();
  /**
   * <code>.org.example.protocol.douyin.PatternRef nameRef = 2;</code>
   * @return The nameRef.
   */
  org.example.protocol.douyin.PatternRef getNameRef();
  /**
   * <code>.org.example.protocol.douyin.PatternRef nameRef = 2;</code>
   */
  org.example.protocol.douyin.PatternRefOrBuilder getNameRefOrBuilder();
}
