// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface TextPieceImageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.TextPieceImage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Image image = 1;</code>
   * @return Whether the image field is set.
   */
  boolean hasImage();
  /**
   * <code>.org.example.protocol.douyin.Image image = 1;</code>
   * @return The image.
   */
  org.example.protocol.douyin.Image getImage();
  /**
   * <code>.org.example.protocol.douyin.Image image = 1;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getImageOrBuilder();

  /**
   * <code>float scalingRate = 2;</code>
   * @return The scalingRate.
   */
  float getScalingRate();
}
