// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface TextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.Text)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string defaultPatter = 2;</code>
   * @return The defaultPatter.
   */
  java.lang.String getDefaultPatter();
  /**
   * <code>string defaultPatter = 2;</code>
   * @return The bytes for defaultPatter.
   */
  com.google.protobuf.ByteString
      getDefaultPatterBytes();

  /**
   * <code>.org.example.protocol.douyin.TextFormat defaultFormat = 3;</code>
   * @return Whether the defaultFormat field is set.
   */
  boolean hasDefaultFormat();
  /**
   * <code>.org.example.protocol.douyin.TextFormat defaultFormat = 3;</code>
   * @return The defaultFormat.
   */
  org.example.protocol.douyin.TextFormat getDefaultFormat();
  /**
   * <code>.org.example.protocol.douyin.TextFormat defaultFormat = 3;</code>
   */
  org.example.protocol.douyin.TextFormatOrBuilder getDefaultFormatOrBuilder();

  /**
   * <code>repeated .org.example.protocol.douyin.TextPiece piecesList = 4;</code>
   */
  java.util.List<org.example.protocol.douyin.TextPiece> 
      getPiecesListList();
  /**
   * <code>repeated .org.example.protocol.douyin.TextPiece piecesList = 4;</code>
   */
  org.example.protocol.douyin.TextPiece getPiecesList(int index);
  /**
   * <code>repeated .org.example.protocol.douyin.TextPiece piecesList = 4;</code>
   */
  int getPiecesListCount();
  /**
   * <code>repeated .org.example.protocol.douyin.TextPiece piecesList = 4;</code>
   */
  java.util.List<? extends org.example.protocol.douyin.TextPieceOrBuilder> 
      getPiecesListOrBuilderList();
  /**
   * <code>repeated .org.example.protocol.douyin.TextPiece piecesList = 4;</code>
   */
  org.example.protocol.douyin.TextPieceOrBuilder getPiecesListOrBuilder(
      int index);
}
