// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface TextEffectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.TextEffect)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.TextEffectDetail portrait = 1;</code>
   * @return Whether the portrait field is set.
   */
  boolean hasPortrait();
  /**
   * <code>.org.example.protocol.douyin.TextEffectDetail portrait = 1;</code>
   * @return The portrait.
   */
  org.example.protocol.douyin.TextEffectDetail getPortrait();
  /**
   * <code>.org.example.protocol.douyin.TextEffectDetail portrait = 1;</code>
   */
  org.example.protocol.douyin.TextEffectDetailOrBuilder getPortraitOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.TextEffectDetail landscape = 2;</code>
   * @return Whether the landscape field is set.
   */
  boolean hasLandscape();
  /**
   * <code>.org.example.protocol.douyin.TextEffectDetail landscape = 2;</code>
   * @return The landscape.
   */
  org.example.protocol.douyin.TextEffectDetail getLandscape();
  /**
   * <code>.org.example.protocol.douyin.TextEffectDetail landscape = 2;</code>
   */
  org.example.protocol.douyin.TextEffectDetailOrBuilder getLandscapeOrBuilder();
}
