// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface UpdateFanTicketMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.UpdateFanTicketMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return Whether the common field is set.
   */
  boolean hasCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   * @return The common.
   */
  org.example.protocol.douyin.Common getCommon();
  /**
   * <code>.org.example.protocol.douyin.Common common = 1;</code>
   */
  org.example.protocol.douyin.CommonOrBuilder getCommonOrBuilder();

  /**
   * <code>string roomFanTicketCountText = 2;</code>
   * @return The roomFanTicketCountText.
   */
  java.lang.String getRoomFanTicketCountText();
  /**
   * <code>string roomFanTicketCountText = 2;</code>
   * @return The bytes for roomFanTicketCountText.
   */
  com.google.protobuf.ByteString
      getRoomFanTicketCountTextBytes();

  /**
   * <code>uint64 roomFanTicketCount = 3;</code>
   * @return The roomFanTicketCount.
   */
  long getRoomFanTicketCount();

  /**
   * <code>bool forceUpdate = 4;</code>
   * @return The forceUpdate.
   */
  boolean getForceUpdate();
}
