// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>uint64 shortId = 2;</code>
   * @return The shortId.
   */
  long getShortId();

  /**
   * <code>string nickName = 3;</code>
   * @return The nickName.
   */
  java.lang.String getNickName();
  /**
   * <code>string nickName = 3;</code>
   * @return The bytes for nickName.
   */
  com.google.protobuf.ByteString
      getNickNameBytes();

  /**
   * <code>uint32 gender = 4;</code>
   * @return The gender.
   */
  int getGender();

  /**
   * <code>string Signature = 5;</code>
   * @return The signature.
   */
  java.lang.String getSignature();
  /**
   * <code>string Signature = 5;</code>
   * @return The bytes for signature.
   */
  com.google.protobuf.ByteString
      getSignatureBytes();

  /**
   * <code>uint32 Level = 6;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>uint64 Birthday = 7;</code>
   * @return The birthday.
   */
  long getBirthday();

  /**
   * <code>string Telephone = 8;</code>
   * @return The telephone.
   */
  java.lang.String getTelephone();
  /**
   * <code>string Telephone = 8;</code>
   * @return The bytes for telephone.
   */
  com.google.protobuf.ByteString
      getTelephoneBytes();

  /**
   * <code>.org.example.protocol.douyin.Image AvatarThumb = 9;</code>
   * @return Whether the avatarThumb field is set.
   */
  boolean hasAvatarThumb();
  /**
   * <code>.org.example.protocol.douyin.Image AvatarThumb = 9;</code>
   * @return The avatarThumb.
   */
  org.example.protocol.douyin.Image getAvatarThumb();
  /**
   * <code>.org.example.protocol.douyin.Image AvatarThumb = 9;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getAvatarThumbOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Image AvatarMedium = 10;</code>
   * @return Whether the avatarMedium field is set.
   */
  boolean hasAvatarMedium();
  /**
   * <code>.org.example.protocol.douyin.Image AvatarMedium = 10;</code>
   * @return The avatarMedium.
   */
  org.example.protocol.douyin.Image getAvatarMedium();
  /**
   * <code>.org.example.protocol.douyin.Image AvatarMedium = 10;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getAvatarMediumOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Image AvatarLarge = 11;</code>
   * @return Whether the avatarLarge field is set.
   */
  boolean hasAvatarLarge();
  /**
   * <code>.org.example.protocol.douyin.Image AvatarLarge = 11;</code>
   * @return The avatarLarge.
   */
  org.example.protocol.douyin.Image getAvatarLarge();
  /**
   * <code>.org.example.protocol.douyin.Image AvatarLarge = 11;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getAvatarLargeOrBuilder();

  /**
   * <code>bool Verified = 12;</code>
   * @return The verified.
   */
  boolean getVerified();

  /**
   * <code>uint32 Experience = 13;</code>
   * @return The experience.
   */
  int getExperience();

  /**
   * <code>string city = 14;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 14;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>int32 Status = 15;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>uint64 CreateTime = 16;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <code>uint64 ModifyTime = 17;</code>
   * @return The modifyTime.
   */
  long getModifyTime();

  /**
   * <code>uint32 Secret = 18;</code>
   * @return The secret.
   */
  int getSecret();

  /**
   * <code>string ShareQrcodeUri = 19;</code>
   * @return The shareQrcodeUri.
   */
  java.lang.String getShareQrcodeUri();
  /**
   * <code>string ShareQrcodeUri = 19;</code>
   * @return The bytes for shareQrcodeUri.
   */
  com.google.protobuf.ByteString
      getShareQrcodeUriBytes();

  /**
   * <code>uint32 IncomeSharePercent = 20;</code>
   * @return The incomeSharePercent.
   */
  int getIncomeSharePercent();

  /**
   * <code>repeated .org.example.protocol.douyin.Image BadgeImageList = 21;</code>
   */
  java.util.List<org.example.protocol.douyin.Image> 
      getBadgeImageListList();
  /**
   * <code>repeated .org.example.protocol.douyin.Image BadgeImageList = 21;</code>
   */
  org.example.protocol.douyin.Image getBadgeImageList(int index);
  /**
   * <code>repeated .org.example.protocol.douyin.Image BadgeImageList = 21;</code>
   */
  int getBadgeImageListCount();
  /**
   * <code>repeated .org.example.protocol.douyin.Image BadgeImageList = 21;</code>
   */
  java.util.List<? extends org.example.protocol.douyin.ImageOrBuilder> 
      getBadgeImageListOrBuilderList();
  /**
   * <code>repeated .org.example.protocol.douyin.Image BadgeImageList = 21;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getBadgeImageListOrBuilder(
      int index);

  /**
   * <code>.org.example.protocol.douyin.FollowInfo FollowInfo = 22;</code>
   * @return Whether the followInfo field is set.
   */
  boolean hasFollowInfo();
  /**
   * <code>.org.example.protocol.douyin.FollowInfo FollowInfo = 22;</code>
   * @return The followInfo.
   */
  org.example.protocol.douyin.FollowInfo getFollowInfo();
  /**
   * <code>.org.example.protocol.douyin.FollowInfo FollowInfo = 22;</code>
   */
  org.example.protocol.douyin.FollowInfoOrBuilder getFollowInfoOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.PayGrade PayGrade = 23;</code>
   * @return Whether the payGrade field is set.
   */
  boolean hasPayGrade();
  /**
   * <code>.org.example.protocol.douyin.PayGrade PayGrade = 23;</code>
   * @return The payGrade.
   */
  org.example.protocol.douyin.PayGrade getPayGrade();
  /**
   * <code>.org.example.protocol.douyin.PayGrade PayGrade = 23;</code>
   */
  org.example.protocol.douyin.PayGradeOrBuilder getPayGradeOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.FansClub FansClub = 24;</code>
   * @return Whether the fansClub field is set.
   */
  boolean hasFansClub();
  /**
   * <code>.org.example.protocol.douyin.FansClub FansClub = 24;</code>
   * @return The fansClub.
   */
  org.example.protocol.douyin.FansClub getFansClub();
  /**
   * <code>.org.example.protocol.douyin.FansClub FansClub = 24;</code>
   */
  org.example.protocol.douyin.FansClubOrBuilder getFansClubOrBuilder();

  /**
   * <pre>
   *  Border Border = 25;
   * </pre>
   *
   * <code>string SpecialId = 26;</code>
   * @return The specialId.
   */
  java.lang.String getSpecialId();
  /**
   * <pre>
   *  Border Border = 25;
   * </pre>
   *
   * <code>string SpecialId = 26;</code>
   * @return The bytes for specialId.
   */
  com.google.protobuf.ByteString
      getSpecialIdBytes();

  /**
   * <code>.org.example.protocol.douyin.Image AvatarBorder = 27;</code>
   * @return Whether the avatarBorder field is set.
   */
  boolean hasAvatarBorder();
  /**
   * <code>.org.example.protocol.douyin.Image AvatarBorder = 27;</code>
   * @return The avatarBorder.
   */
  org.example.protocol.douyin.Image getAvatarBorder();
  /**
   * <code>.org.example.protocol.douyin.Image AvatarBorder = 27;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getAvatarBorderOrBuilder();

  /**
   * <code>.org.example.protocol.douyin.Image Medal = 28;</code>
   * @return Whether the medal field is set.
   */
  boolean hasMedal();
  /**
   * <code>.org.example.protocol.douyin.Image Medal = 28;</code>
   * @return The medal.
   */
  org.example.protocol.douyin.Image getMedal();
  /**
   * <code>.org.example.protocol.douyin.Image Medal = 28;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getMedalOrBuilder();

  /**
   * <code>repeated .org.example.protocol.douyin.Image RealTimeIconsList = 29;</code>
   */
  java.util.List<org.example.protocol.douyin.Image> 
      getRealTimeIconsListList();
  /**
   * <code>repeated .org.example.protocol.douyin.Image RealTimeIconsList = 29;</code>
   */
  org.example.protocol.douyin.Image getRealTimeIconsList(int index);
  /**
   * <code>repeated .org.example.protocol.douyin.Image RealTimeIconsList = 29;</code>
   */
  int getRealTimeIconsListCount();
  /**
   * <code>repeated .org.example.protocol.douyin.Image RealTimeIconsList = 29;</code>
   */
  java.util.List<? extends org.example.protocol.douyin.ImageOrBuilder> 
      getRealTimeIconsListOrBuilderList();
  /**
   * <code>repeated .org.example.protocol.douyin.Image RealTimeIconsList = 29;</code>
   */
  org.example.protocol.douyin.ImageOrBuilder getRealTimeIconsListOrBuilder(
      int index);

  /**
   * <code>string displayId = 38;</code>
   * @return The displayId.
   */
  java.lang.String getDisplayId();
  /**
   * <code>string displayId = 38;</code>
   * @return The bytes for displayId.
   */
  com.google.protobuf.ByteString
      getDisplayIdBytes();

  /**
   * <code>string secUid = 46;</code>
   * @return The secUid.
   */
  java.lang.String getSecUid();
  /**
   * <code>string secUid = 46;</code>
   * @return The bytes for secUid.
   */
  com.google.protobuf.ByteString
      getSecUidBytes();

  /**
   * <code>uint64 fanTicketCount = 1022;</code>
   * @return The fanTicketCount.
   */
  long getFanTicketCount();

  /**
   * <code>string idStr = 1028;</code>
   * @return The idStr.
   */
  java.lang.String getIdStr();
  /**
   * <code>string idStr = 1028;</code>
   * @return The bytes for idStr.
   */
  com.google.protobuf.ByteString
      getIdStrBytes();

  /**
   * <code>uint32 ageRange = 1045;</code>
   * @return The ageRange.
   */
  int getAgeRange();
}
