// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

/**
 * Protobuf type {@code org.example.protocol.douyin.UserBadge}
 */
public final class UserBadge extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.example.protocol.douyin.UserBadge)
    UserBadgeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserBadge.newBuilder() to construct.
  private UserBadge(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserBadge() {
    title_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserBadge();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.protocol.douyin.Douyin.internal_static_org_example_protocol_douyin_UserBadge_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetIcons();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.protocol.douyin.Douyin.internal_static_org_example_protocol_douyin_UserBadge_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.protocol.douyin.UserBadge.class, org.example.protocol.douyin.UserBadge.Builder.class);
  }

  public static final int ICONS_FIELD_NUMBER = 1;
  private static final class IconsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, org.example.protocol.douyin.Image> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, org.example.protocol.douyin.Image>newDefaultInstance(
                org.example.protocol.douyin.Douyin.internal_static_org_example_protocol_douyin_UserBadge_IconsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                org.example.protocol.douyin.Image.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.Integer, org.example.protocol.douyin.Image> icons_;
  private com.google.protobuf.MapField<java.lang.Integer, org.example.protocol.douyin.Image>
  internalGetIcons() {
    if (icons_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          IconsDefaultEntryHolder.defaultEntry);
    }
    return icons_;
  }
  public int getIconsCount() {
    return internalGetIcons().getMap().size();
  }
  /**
   * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
   */
  @java.lang.Override
  public boolean containsIcons(
      int key) {

    return internalGetIcons().getMap().containsKey(key);
  }
  /**
   * Use {@link #getIconsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, org.example.protocol.douyin.Image> getIcons() {
    return getIconsMap();
  }
  /**
   * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.Integer, org.example.protocol.douyin.Image> getIconsMap() {
    return internalGetIcons().getMap();
  }
  /**
   * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
org.example.protocol.douyin.Image getIconsOrDefault(
      int key,
      /* nullable */
org.example.protocol.douyin.Image defaultValue) {

    java.util.Map<java.lang.Integer, org.example.protocol.douyin.Image> map =
        internalGetIcons().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
   */
  @java.lang.Override
  public org.example.protocol.douyin.Image getIconsOrThrow(
      int key) {

    java.util.Map<java.lang.Integer, org.example.protocol.douyin.Image> map =
        internalGetIcons().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetIcons(),
        IconsDefaultEntryHolder.defaultEntry,
        1);
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.Integer, org.example.protocol.douyin.Image> entry
         : internalGetIcons().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, org.example.protocol.douyin.Image>
      icons__ = IconsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, icons__);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.protocol.douyin.UserBadge)) {
      return super.equals(obj);
    }
    org.example.protocol.douyin.UserBadge other = (org.example.protocol.douyin.UserBadge) obj;

    if (!internalGetIcons().equals(
        other.internalGetIcons())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetIcons().getMap().isEmpty()) {
      hash = (37 * hash) + ICONS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetIcons().hashCode();
    }
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.protocol.douyin.UserBadge parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protocol.douyin.UserBadge parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protocol.douyin.UserBadge parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protocol.douyin.UserBadge parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protocol.douyin.UserBadge parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protocol.douyin.UserBadge parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protocol.douyin.UserBadge parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.protocol.douyin.UserBadge parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.protocol.douyin.UserBadge parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.protocol.douyin.UserBadge parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.protocol.douyin.UserBadge parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.protocol.douyin.UserBadge parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.protocol.douyin.UserBadge prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.example.protocol.douyin.UserBadge}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.example.protocol.douyin.UserBadge)
      org.example.protocol.douyin.UserBadgeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.protocol.douyin.Douyin.internal_static_org_example_protocol_douyin_UserBadge_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetIcons();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableIcons();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.protocol.douyin.Douyin.internal_static_org_example_protocol_douyin_UserBadge_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.protocol.douyin.UserBadge.class, org.example.protocol.douyin.UserBadge.Builder.class);
    }

    // Construct using org.example.protocol.douyin.UserBadge.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableIcons().clear();
      title_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.protocol.douyin.Douyin.internal_static_org_example_protocol_douyin_UserBadge_descriptor;
    }

    @java.lang.Override
    public org.example.protocol.douyin.UserBadge getDefaultInstanceForType() {
      return org.example.protocol.douyin.UserBadge.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.protocol.douyin.UserBadge build() {
      org.example.protocol.douyin.UserBadge result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.protocol.douyin.UserBadge buildPartial() {
      org.example.protocol.douyin.UserBadge result = new org.example.protocol.douyin.UserBadge(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.protocol.douyin.UserBadge result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.icons_ = internalGetIcons();
        result.icons_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.title_ = title_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.protocol.douyin.UserBadge) {
        return mergeFrom((org.example.protocol.douyin.UserBadge)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.protocol.douyin.UserBadge other) {
      if (other == org.example.protocol.douyin.UserBadge.getDefaultInstance()) return this;
      internalGetMutableIcons().mergeFrom(
          other.internalGetIcons());
      bitField0_ |= 0x00000001;
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.Integer, org.example.protocol.douyin.Image>
              icons__ = input.readMessage(
                  IconsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableIcons().getMutableMap().put(
                  icons__.getKey(), icons__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.Integer, org.example.protocol.douyin.Image> icons_;
    private com.google.protobuf.MapField<java.lang.Integer, org.example.protocol.douyin.Image>
        internalGetIcons() {
      if (icons_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            IconsDefaultEntryHolder.defaultEntry);
      }
      return icons_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, org.example.protocol.douyin.Image>
        internalGetMutableIcons() {
      if (icons_ == null) {
        icons_ = com.google.protobuf.MapField.newMapField(
            IconsDefaultEntryHolder.defaultEntry);
      }
      if (!icons_.isMutable()) {
        icons_ = icons_.copy();
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return icons_;
    }
    public int getIconsCount() {
      return internalGetIcons().getMap().size();
    }
    /**
     * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
     */
    @java.lang.Override
    public boolean containsIcons(
        int key) {

      return internalGetIcons().getMap().containsKey(key);
    }
    /**
     * Use {@link #getIconsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, org.example.protocol.douyin.Image> getIcons() {
      return getIconsMap();
    }
    /**
     * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, org.example.protocol.douyin.Image> getIconsMap() {
      return internalGetIcons().getMap();
    }
    /**
     * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
org.example.protocol.douyin.Image getIconsOrDefault(
        int key,
        /* nullable */
org.example.protocol.douyin.Image defaultValue) {

      java.util.Map<java.lang.Integer, org.example.protocol.douyin.Image> map =
          internalGetIcons().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
     */
    @java.lang.Override
    public org.example.protocol.douyin.Image getIconsOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, org.example.protocol.douyin.Image> map =
          internalGetIcons().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearIcons() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableIcons().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
     */
    public Builder removeIcons(
        int key) {

      internalGetMutableIcons().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, org.example.protocol.douyin.Image>
        getMutableIcons() {
      bitField0_ |= 0x00000001;
      return internalGetMutableIcons().getMutableMap();
    }
    /**
     * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
     */
    public Builder putIcons(
        int key,
        org.example.protocol.douyin.Image value) {

      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableIcons().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
     */
    public Builder putAllIcons(
        java.util.Map<java.lang.Integer, org.example.protocol.douyin.Image> values) {
      internalGetMutableIcons().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.example.protocol.douyin.UserBadge)
  }

  // @@protoc_insertion_point(class_scope:org.example.protocol.douyin.UserBadge)
  private static final org.example.protocol.douyin.UserBadge DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.protocol.douyin.UserBadge();
  }

  public static org.example.protocol.douyin.UserBadge getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserBadge>
      PARSER = new com.google.protobuf.AbstractParser<UserBadge>() {
    @java.lang.Override
    public UserBadge parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserBadge> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserBadge> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.protocol.douyin.UserBadge getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

