// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: douyin.proto

package org.example.protocol.douyin;

public interface UserBadgeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.protocol.douyin.UserBadge)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
   */
  int getIconsCount();
  /**
   * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
   */
  boolean containsIcons(
      int key);
  /**
   * Use {@link #getIconsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, org.example.protocol.douyin.Image>
  getIcons();
  /**
   * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
   */
  java.util.Map<java.lang.Integer, org.example.protocol.douyin.Image>
  getIconsMap();
  /**
   * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
   */
  /* nullable */
org.example.protocol.douyin.Image getIconsOrDefault(
      int key,
      /* nullable */
org.example.protocol.douyin.Image defaultValue);
  /**
   * <code>map&lt;int32, .org.example.protocol.douyin.Image&gt; icons = 1;</code>
   */
  org.example.protocol.douyin.Image getIconsOrThrow(
      int key);

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();
}
